awslabs/graphstorm

- .github/workflow_scripts/e2e_check.sh
- .github/workflow_scripts/e2e_mgpu_check.sh
- .github/workflow_scripts/lint_check.sh
- .github/workflow_scripts/pytest_check.sh
- .github/workflows/continuous-integration.yml
- graphstorm_job.sh
- submitJob.py
***Description of changes:***
Making changes to CI, removing pre-cloned repository pre-OSS.
> OSS CI Updates

- python/graphstorm/config/argument.py
Fix minor bugs to fix the CI pipeline
> Fix CI pipeline

- README.md
> Update readme to define GraphStorm.

- tests/end2end-tests/graphstorm-ec/mgpu_test.sh
- tests/end2end-tests/graphstorm-er/mgpu_test.sh
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
- tests/end2end-tests/graphstorm-nc/mgpu_test.sh
We save too much temporal models and outputs during CI 
Remove them temporal models and outputs from disk
> [Fix CI] Fix CI out of disk space problem

- .github/workflows/continuous-integration.yml
**Description of changes:** LowerCase not handled by GitHub actions, fixing the same
> CI Label Fix

- python/graphstorm/gconstruct/README.md
- tests/end2end-tests/data_process/test.sh
Provide the instruction of how to run the graph construction script correctly.
> Fix how to run the graph construction script.

- python/graphstorm/gconstruct/construct_graph.py
- python/graphstorm/utils.py
- tests/unit-tests/test_construct_graph.py
The graph construction pipeline cannot handle large graphs. This PR is to optimize the resource management to enable it to process a graph with 1B nodes and 10B edges.
> Optimize graph construction pipeline

- inference_scripts/ep_infer/ep_infer_gnn.py
- inference_scripts/ep_infer/ep_infer_lm.py
- inference_scripts/lp_infer/lp_infer_gnn.py
- inference_scripts/lp_infer/lp_infer_lm.py
- inference_scripts/np_infer/np_infer_gnn.py
- python/graphstorm/config/argument.py
- tests/end2end-tests/data_process/data_gen.py
> Cleanup inference code

- docker/Dockerfile.local
- requirements.txt
**Description of changes:**
Updated OGB package version
> Fix OGB Dataset unzipping issue

- python/graphstorm/eval/evaluator.py
- python/graphstorm/model/gnn.py
- python/graphstorm/model/utils.py
- python/graphstorm/trainer/gsgnn_trainer.py
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
- tests/end2end-tests/graphstorm-nc/check_emb.py
- tests/unit-tests/test_model_save_load.py
This PR saves and loads learnable sparse embeddings in a distributed manner. Each trainer (GPU) will be responsible to saving part of sparse embeddings. We assume the data is writen into a shared file system.
#28 
> Save and Load learnable sparse embedding in a distributed manner

- python/graphstorm/gconstruct/construct_graph.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/test.sh
- tests/unit-tests/test_construct_graph.py
When constructing a graph with large features, we can store the node/edge features in external memory during the graph construction. This allows us to construct a much larger graph.
> Graph construction with external memory support

- python/graphstorm/gconstruct/__init__.py
- python/graphstorm/gconstruct/construct_graph.py
- tests/end2end-tests/data_process/data_gen.py
- tests/unit-tests/test_construct_graph.py
> Add JSON support

- python/graphstorm/gconstruct/README.md
- python/graphstorm/gconstruct/construct_graph.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/gen_test_graphs.py
- tests/unit-tests/test_construct_graph.py
The construct_graph.py has some naming bugs. 
- Add a new dummy customer data generation codes
- Fix a few naming issues in construct_grapy.py and data_gen.py.
> [Fix] Test graph construction and fix a few naming bugs

- setup.py
We should install `scikit-learn` instead of `sklearn`
> Fix a bug in pip install

- python/graphstorm/inference/ep_infer.py
- python/graphstorm/inference/np_infer.py
- python/graphstorm/model/gnn.py
- python/graphstorm/model/utils.py
- tests/unit-tests/test_utils.py
*Issue #92, if available:*
1. Use rank 0 to makedirs and chmod to 777;
2. Make directories and chmod before save sparse embeddings.
3. Apply the same method for saving node representations, node/edge predictions.
> [Bug Fix] Fix folder permission issue in NFS setting

- python/graphstorm/model/gnn.py
To many prints will cause CI error.
Only rank 0 should print model saving prints.
> Reduce save model prints

- README.md
- inference_scripts/ep_infer/ep_infer_gnn.py
- inference_scripts/ep_infer/ep_infer_lm.py
- inference_scripts/lp_infer/lp_infer_gnn.py
- inference_scripts/lp_infer/lp_infer_lm.py
- inference_scripts/np_infer/np_infer_gnn.py
- python/graphstorm/config/argument.py
- python/graphstorm/gsf.py
- tests/end2end-tests/graphstorm-ec/mgpu_test.sh
- tests/end2end-tests/graphstorm-ec/test.sh
- tests/end2end-tests/graphstorm-nc/test.sh
- tests/unit-tests/test_config.py
- tests/unit-tests/test_gnn.py
- training_scripts/gsgnn_ep/gsgnn_ep.py
- training_scripts/gsgnn_ep/gsgnn_lm_ep.py
- training_scripts/gsgnn_lp/gsgnn_lm_lp.py
- training_scripts/gsgnn_lp/gsgnn_lp.py
- training_scripts/gsgnn_np/gsgnn_np.py
#99 
Rename feat_name to node_feat_name
> Change argument feat_name to node_feat_name

- python/graphstorm/gconstruct/file_io.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/test_data.py
Fix a bug in graph construction when the task is link prediction.
> Fix a bug in graph construction

- inference_scripts/ep_infer/test_ec_infer.yaml
- inference_scripts/np_infer/arxiv_nc.yaml
- inference_scripts/np_infer/ml_nc_infer.yaml
- inference_scripts/np_infer/ml_nc_text_infer.yaml
- python/graphstorm/config/argument.py
- python/graphstorm/inference/ep_infer.py
- python/graphstorm/inference/np_infer.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- tests/end2end-tests/graphstorm-nc/mgpu_test.sh
- tests/unit-tests/test_config.py
> [Config] Rename save-predict-path/save_predict_path to save-prediction-path/save_prediction_path.

- examples/customized_models/HGT/hgt_nc.py
- python/graphstorm/config/argument.py
- python/graphstorm/eval/evaluator.py
- python/graphstorm/model/node_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- tests/end2end-tests/data_process/ml_ec_text.yaml
- tests/end2end-tests/graphstorm-ec/test.sh
- tests/end2end-tests/graphstorm-lp/test.sh
- tests/unit-tests/test_config.py
- tests/unit-tests/test_dist_eval.py
- tests/unit-tests/test_evaluator.py
- training_scripts/gsgnn_ep/ml_ec.yaml
- training_scripts/gsgnn_ep/ml_ec_text.yaml
- training_scripts/gsgnn_ep/ml_er.yaml
- training_scripts/gsgnn_ep/ml_lm_ec.yaml
- training_scripts/gsgnn_ep/test_ec.yaml
- training_scripts/gsgnn_lp/mag_lp.yaml
Resolves https://github.com/awslabs/graphstorm/issues/143
> [Config] Rename `evaluation_frequency` to `eval_frequency`

- python/graphstorm/config/argument.py
- tests/unit-tests/test_config.py
> [Config] Removing separate_eval

- python/graphstorm/run/launch.py
> Fix launch cleanup_process error

- tools/README.md
- tools/kill_cleanup_disttrain.sh
Update the tool/kill_cleanup_disttrain.sh to include port number as an argument.
> Update Kill&Cleanup Script

- python/graphstorm/config/argument.py
> Add more checks for the input arguments.

- python/graphstorm/gconstruct/README.md
- python/graphstorm/gconstruct/construct_graph.py
- python/graphstorm/gconstruct/utils.py
- tests/unit-tests/test_construct_graph.py
> Save node ID and edge ID mapping by default during graph construction

- python/graphstorm/gconstruct/construct_graph.py
- python/graphstorm/gconstruct/transform.py
- python/graphstorm/gconstruct/utils.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/movielens_bert.json
- tests/end2end-tests/data_process/movielens_test.sh
- tests/end2end-tests/data_process/test_data.py
- tests/unit-tests/test_construct_graph.py
> Compute BERT embeddings in the graph construction

- examples/acm_data.py
- examples/customized_models/HGT/README.md
- examples/customized_models/HGT/acm_nc.yaml
- examples/customized_models/HGT/hgt_nc.py
- python/graphstorm/model/__init__.py
- python/graphstorm/trainer/gsgnn_trainer.py
> Update Use Your Own Model codes and readme

- python/graphstorm/gconstruct/README.md
- python/graphstorm/gconstruct/construct_graph.py
- tests/end2end-tests/data_process/movielens_test.sh
- tests/end2end-tests/data_process/test.sh
> Fix the argument name of graph construction

- python/graphstorm/gconstruct/construct_graph.py
- tests/end2end-tests/data_process/movielens_test.sh
> add random partition.

- examples/customized_models/HGT/acm_nc.yaml
- examples/customized_models/HGT/hgt_nc.py
To fit the revised Use Your Own Model docs, make a few change of the hgt_nc.py and yaml file.
> Update hgt_nc code to match new Use Your Own Model docs

- examples/customized_models/HGT/README.md
- examples/customized_models/HGT/acm_nc.yaml
- examples/customized_models/HGT/hgt_nc.py
*Issue #177 , if available:*
Fix the HGT example's unused variables and update the README file to reflect the changes of the new launch method.
> [Fix ] Fix HGT example issue and update readme to use the latest launch method

- README.md
- examples/customized_models/HGT/README.md
- tests/end2end-tests/create_data.sh
- tools/README.md
- tools/partition_graph.py
- tools/partition_graph_lp.py
Make all argument in the same format, using "-"
> [Feature] Update graph partition arguments to use "-" not "_

- README.md
- tests/end2end-tests/tools/test_mem_est.sh
- tools/gen_mag_dataset.py
- tools/gen_ogb_dataset.py
- tools/gsf_mem_est.py
- tools/regression_tests_utils.py
For argument consistency, change all tools' arguments to use -, not _.
> change tools arguments to use -, not _

- README.md
- setup.py
To have pip package to use required dependency, need to fix the versions of these dependencies.
> [Fix] Update setup adding fixed dependency versions

- README.md
- docker/Dockerfile.local
- docker/README.md
- docker/build_docker_oss4local.sh
- setup.py
Merge the latest update in main into the v0.1 branch
> Merge the latest update in main into the v0.1

- README.md
Add multiple sampler issue in limitations
> Update limitations README.md

- python/graphstorm/config/argument.py
- python/graphstorm/utils.py
Different Pytorch version has a different local rank argument. We need to test the Pytorch major version to decide the right argument name.
> Fix local rank

- python/graphstorm/gconstruct/construct_graph.py
- python/graphstorm/gconstruct/id_map.py
- python/graphstorm/gconstruct/transform.py
- python/graphstorm/gconstruct/utils.py
- python/graphstorm/utils.py
We should use `logging` to print messages so that we can set the logging level to hide some messages.
Fix the issue: https://github.com/awslabs/graphstorm/issues/204
> Use logging to print messages.

- sagemaker/launch/launch_infer.py
- sagemaker/launch/launch_train.py
- sagemaker/run/infer_entry.py
- sagemaker/run/train_entry.py
> Fix typo of SageMaker related files

- tools/README.md
> [Fix] cleanup typo

- python/graphstorm/inference/ep_infer.py
- python/graphstorm/inference/np_infer.py
Fix device referred before define error.
> [Fix] fix device refer before define error

- docs/source/advanced/own-models.rst
- examples/customized_models/HGT/hgt_nc.py
Update HGT example to fit the new predict API.
> [Fix] update HGT to fit the new predict API

- python/graphstorm/gconstruct/file_io.py
- python/graphstorm/gconstruct/transform.py
- python/graphstorm/gconstruct/utils.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/test_data.py
- tests/unit-tests/gconstruct/test_construct_graph.py
> Fix bug of some transform ops do not return float16 data if out_dtype is set to float16

- examples/acm_data.py
- examples/use_your_own_data/acm_lm_nc.yaml
This change include text feature for paper, author, and subject. This example will be used for tutorial of LM.
> [Feature] Modify acm_data.py to include text as node feature

- sagemaker/launch/launch_infer.py
- sagemaker/local/generate_sagemaker_docker_compose.py
This PR further fix the LP no prediction error. And tested with SageMaker CI pipeline.
> [Fix] Further fix SageMaker LP no predictions

- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/trainer/ep_trainer.py
- python/graphstorm/trainer/lp_trainer.py
- python/graphstorm/trainer/np_trainer.py
- python/graphstorm/utils.py
> Update memory profiling support for all training tasks

- README.md
> [Doc] Update readme.

- docker/Dockerfile.local
- docker/sagemaker/Dockerfile.sm
- python/graphstorm/__init__.py
> [Update version] Release 0.1.1

- python/graphstorm/gconstruct/transform.py
- tests/unit-tests/gconstruct/test_transform.py
> [Feature] Categorical feature transform allows some input values are None

- submitJob.py
> Increasing CI time-out value

- python/graphstorm/dataloading/dataloading.py
- python/graphstorm/gsf.py
- tests/end2end-tests/data_process/test.sh
- tests/end2end-tests/graphstorm-ec/mgpu_test.sh
- tests/end2end-tests/graphstorm-er/mgpu_test.sh
> [Bugfix] Support edge feature in edge regression decoder

- python/graphstorm/gconstruct/id_map.py
- tests/end2end-tests/data_process/data_gen.py
- tests/unit-tests/gconstruct/test_construct_graph.py
> Handle the case when input node id dtype is not integer or string

- python/graphstorm/gconstruct/file_io.py
- python/graphstorm/gconstruct/transform.py
- python/graphstorm/gconstruct/utils.py
- tests/end2end-tests/data_process/test_data.py
- tests/unit-tests/gconstruct/test_construct_graph.py
- tests/unit-tests/gconstruct/test_transform.py
> Set default dtype of transformed feature to float32

- python/graphstorm/trainer/ep_trainer.py
- python/graphstorm/trainer/lp_trainer.py
- python/graphstorm/trainer/np_trainer.py
Clean up unused code in the training loop.
> Clean up the training loop

- python/graphstorm/model/edge_gnn.py
- tests/end2end-tests/graphstorm-ec/mgpu_test.sh
The bug is triggered when edge features are used and mini-batch inference is enabled.
> Fix the device mis-match bug.

- python/graphstorm/model/edge_gnn.py
- tests/end2end-tests/graphstorm-ec/mgpu_test.sh
The bug is triggered when edge features are used and mini-batch inference is enabled.
---------
> Fix the device mis-match bug. (#288)

- docs/source/configuration/configuration-gconstruction.rst
- python/graphstorm/model/gnn_encoder_base.py
> Fix typo in doc and add some missing features

- python/graphstorm/model/utils.py
> Fix a bug in loading language model optimizer state

- docker/Dockerfile.local
- docker/sagemaker/Dockerfile.sm
- docs/source/install/env-setup.rst
- docs/source/scale/sagemaker.rst
DGL 1.0.4 provides an optimization on neighbor sampling. Together with #279, the training speed of 2 layer RGCN on MAG dataset on 4 g5.48x reduces can be improved by 2.5X
> Update dgl version to 1.0.4

- sagemaker/README.md
> [Fix] Fix a SageMaker-based gconstruct command typo

- python/graphstorm/sagemaker/sagemaker_infer.py
- python/graphstorm/sagemaker/sagemaker_train.py
> Remove models as we have already uploaded the model

- python/graphstorm/model/gnn_encoder_base.py
- python/graphstorm/run/launch.py
Distributed KVServer always use OMP=1, set to a larger number to leverage multi-core CPU.
> Optimize OMP setting

- docker/Dockerfile.local
- setup.py
[*Issue #, if available:*](https://github.com/awslabs/graphstorm/issues/301)
*Description of changes:* Removing few packages
> #301 - Cleanup unnecessary pip dependencies

- docs/source/configuration/configuration-run.rst
- python/graphstorm/eval/eval_func.py
- tests/end2end-tests/graphstorm-er/test.sh
*Description of changes:* Add evaluation metric MAE for regression tasks.
> Add eval metric mae

- python/graphstorm/dataloading/dataset.py
- python/graphstorm/inference/np_infer.py
- python/graphstorm/model/node_gnn.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- tests/end2end-tests/create_data.sh
- tests/end2end-tests/graphstorm-ec/mgpu_test.sh
- tests/end2end-tests/graphstorm-nc/mgpu_test.sh
- tests/unit-tests/test_dataloading.py
> Allow node classification/regression inference tasks work with graphs without test masks

- python/graphstorm/gconstruct/file_io.py
- tests/end2end-tests/data_process/data_gen.py
- tests/unit-tests/gconstruct/test_construct_graph.py
support csv format for input files.
> Add csv support in the graph construction pipeline.

- examples/mag/mag_lp.yaml
- python/graphstorm/config/argument.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- tests/unit-tests/test_config.py
- training_scripts/gsgnn_np/ml_nc.yaml
We need to verify the correctness of the input arguments as early as possible. This is important when we deal with large datasets.
https://github.com/awslabs/graphstorm/issues/20
> add checks to verify the correctness of the input arguments

- python/graphstorm/config/argument.py
> Fix argument check when encoder type is lm.

- .github/workflow_scripts/e2e_cpu_check.sh
- .github/workflows/continuous-integration.yml
- submitJob.py
Building CI infrastructure for CPU support.
Uses the same infrastructure as done by lint check.
> CI Infra for CPU Support

- .github/workflow_scripts/e2e_cpu_check.sh
So PRs other than CPU support can use the CI pipeline.
> Disable cpu test temporally.

- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
> [BugFix] Fix link prediction inference when the graph does not have train/val/test split

- docker/build_docker_sagemaker.sh
- docker/sagemaker/Dockerfile.sm
- docker/sagemaker/README.md
To pass CI build pipeline, change all uppercase to lowercase in Docker files.
> [Fix] change GPU|CPU to gpu|cpu

- python/graphstorm/sagemaker/sagemaker_infer.py
- python/graphstorm/sagemaker/sagemaker_train.py
- sagemaker/run/gconstruct_entry.py
- sagemaker/run/infer_entry.py
- sagemaker/run/train_entry.py
> Change the location of input data and output data of sagemaker training/inference tasks to /tmp/

- python/graphstorm/sagemaker/sagemaker_infer.py
- python/graphstorm/sagemaker/sagemaker_train.py
Fix the num trainer problem when launching cpu SageMaker Image.
> fixed no cpu num trainer for sagemaker

- python/graphstorm/sagemaker/sagemaker_infer.py
- python/graphstorm/sagemaker/sagemaker_train.py
Reverts awslabs/graphstorm#357
> Revert "fixed no cpu num trainer for sagemaker"

- python/graphstorm/sagemaker/sagemaker_infer.py
- python/graphstorm/sagemaker/sagemaker_train.py
fix num trainer problem for SageMaker cpu image
> Sagemaker cpu trainer

- python/graphstorm/__init__.py
> Fix version of 0.1.2

- examples/customized_models/HGT/acm_nc.yaml
- examples/customized_models/HGT/hgt_nc.py
The CPU modification removed required contents. This PR fix this bug.
> [Fix] Fix HGT bug after CPU modification

- docs/source/configuration/configuration-run.rst
- python/graphstorm/config/argument.py
- python/graphstorm/gsf.py
- python/graphstorm/model/edge_decoder.py
- tests/unit-tests/test_decoder.py
- tests/unit-tests/test_gnn.py
> Add ngnn support for edge decoder

- docs/source/advanced/advanced-usages.rst
- docs/source/configuration/configuration-run.rst
- docs/source/install/env-setup.rst
- docs/source/scale/sagemaker.rst
This version of rst files is the Wiki version.
> [fix] Fix v0.1.2 docs typos and add enhancement

- tools/README.md
Typo in generating ogbn-mag dataset
> Fix Typo in generating ogbn-mag dataset

- docs/source/configuration/configuration-run.rst
- python/graphstorm/config/argument.py
- python/graphstorm/model/loss_func.py
- tests/unit-tests/test_config.py
> Support cross class weight for multilabel classification

- python/graphstorm/eval/eval_func.py
> Add support of per class roc auc report for multi-label multi-class classification tasks.

- tests/end2end-tests/data_process/data_gen.py
The existing random node id generation may sometime fail the CI. This PR fix the problem.
> [BugFix] Fix random node id gen in CI.

- graphstorm-processing/graphstorm_processing/constants.py
- graphstorm-processing/graphstorm_processing/distributed_executor.py
- graphstorm-processing/scripts/convert_gconstruct_config.py
- graphstorm-processing/scripts/run_distributed_processing.py
- graphstorm-processing/scripts/script_utils.py
- tests/lint/pylintrc
> [GSProcessing] GSProcessing PR2: Entrypoint and SageMaker script for processing.

- python/graphstorm/dataloading/dataloading.py
- python/graphstorm/dataloading/utils.py
- tests/unit-tests/test_dataloading.py
> [Bugfix] Avoid trim data for validation and test datasets

- graphstorm-processing/graphstorm_processing/distributed_executor.py
- graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
- graphstorm-processing/graphstorm_processing/graph_loaders/heterogeneous_graphloader.py
- graphstorm-processing/graphstorm_processing/graph_loaders/loader_base.py
- graphstorm-processing/tests/test_dist_heterogenous_loader.py
#294 
The core class that performs the processing of the graph structure and features.
> GSProcessing PR-3: Distributed Heterogeneous Graph Loader

- .github/workflows/continuous-integration.yml
Allow developer to add ready tag after they creating the PR request
> add labeled

- graphstorm-processing/docker-entry.sh
- graphstorm-processing/docker/0.1.0/Dockerfile.cpu
- graphstorm-processing/docker/README.md
- graphstorm-processing/docker/build_gsprocessing_image.sh
- graphstorm-processing/docker/push_gsprocessing_image.sh
- graphstorm-processing/graphstorm_processing/data_transformations/s3_utils.py
- graphstorm-processing/graphstorm_processing/distributed_executor.py
- graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
- graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
- graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
- graphstorm-processing/pyproject.toml
- graphstorm-processing/scripts/run_distributed_processing.py
* Add Docker-related files
* Add code utilities used by `DistHeterogeneousGraphLoader`.
> [GSProcessing] Add Docker-related files and code utilities.

- python/graphstorm/model/utils.py
*Issue #, if available:* #344
*Description of changes:* load optimizer checkpoint to cpu to avoid potential GPU OOM error.
> Bug fix for restoring optimizer to cpu

- docs/source/advanced/own-models.rst
- examples/customized_models/HGT/hgt_nc.py
- python/graphstorm/config/argument.py
- python/graphstorm/gsf.py
- python/graphstorm/inference/ep_infer.py
- python/graphstorm/inference/graphstorm_infer.py
- python/graphstorm/inference/lp_infer.py
- python/graphstorm/inference/np_infer.py
- python/graphstorm/model/utils.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- python/graphstorm/tracker/graphstorm_tracker.py
- python/graphstorm/tracker/sagemaker_tracker.py
- python/graphstorm/trainer/ep_trainer.py
- python/graphstorm/trainer/glem_np_trainer.py
- python/graphstorm/trainer/gsgnn_trainer.py
- python/graphstorm/trainer/lp_trainer.py
- python/graphstorm/trainer/np_trainer.py
- tests/end2end-tests/custom-gnn/train.py
- tests/unit-tests/test_config.py
GraphStorm can identify the rank automatically. We don't need to have a rank argument in many classes.
> Remove unnecessary rank argument.

- graphstorm-processing/docker/0.1.0/Dockerfile.cpu
- graphstorm-processing/docker/push_gsprocessing_image.sh
- graphstorm-processing/graphstorm_processing/distributed_executor.py
- graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
- graphstorm-processing/pyproject.toml
- graphstorm-processing/scripts/run_distributed_processing.py
https://github.com/awslabs/graphstorm/security/dependabot/3
https://github.com/awslabs/graphstorm/security/dependabot/4
https://github.com/awslabs/graphstorm/security/dependabot/5
Move GSProcessing to Spark 3.3.x and add couple of small fixes for issues that were introduced during PR changes.
> [GSProcessing] Move to Spark 3.3

- python/graphstorm/config/argument.py
The default value of fanout should be a list.
> Fix a bug in the default value of fanout

- graphstorm-processing/graphstorm_processing/repartition_files.py
- graphstorm-processing/scripts/run_repartitioning.py
- graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
- graphstorm-processing/tests/test_repartition_files.py
* Add repartitioning code. This step is needed after processing to ensure our data match the assumptions of the dist-processing pipeline.
* We include one in-memory and one file streaming implementation. Currently using in-memory, could make this a user option.
* Include tests and SageMaker launch script.
> [GSProcessing] Add repartitioning code

- python/graphstorm/config/argument.py
We need to set up the logging as early as possible. otherwise, the log messages are not printed out correctly.
> Fix logging

- graphstorm-processing/graphstorm_processing/data_transformations/s3_utils.py
- graphstorm-processing/graphstorm_processing/distributed_executor.py
* Small improvements to the way we parse files for config from S3. 
* Check for version for both gconstruct and gsprocessing JSON files.
> [GSProcessing] Small improvements to version check and config download

- python/graphstorm/config/argument.py
- python/graphstorm/dataloading/dataset.py
- python/graphstorm/model/gnn.py
- python/graphstorm/run/launch.py
Fix an issue in logging and print out more information.
> Fix the logging

- examples/mag/README.md
- examples/mag/mag_glem_nc.yaml
- examples/mag/mag_glem_w_pretrain.yml
*Description of changes:* Updated MAG example with GLEM instructions
> Updated MAG example with GLEM instructions

- python/graphstorm/model/edge_gnn.py
- python/graphstorm/trainer/ep_trainer.py
> [Bug Fix] Change on EC test

- python/graphstorm/dataloading/dataset.py
Add Doc String for dataloading.dataset
> [Doc] Add Doc String for graphstorm.dataloading.dataset

- python/graphstorm/dataloading/dataset.py
Reverts awslabs/graphstorm#470
> Revert "[Doc] Add Doc String for graphstorm.dataloading.dataset"

- python/graphstorm/dataloading/dataloading.py
Add doc string for graphstorm.dataloading.dataloading
> [Doc] Add Doc String for graphstorm.dataloading.dataloading

- python/graphstorm/trainer/ep_trainer.py
- python/graphstorm/trainer/glem_np_trainer.py
- python/graphstorm/trainer/gsgnn_trainer.py
- python/graphstorm/trainer/lp_trainer.py
- python/graphstorm/trainer/np_trainer.py
> [Doc] Add docstrings for trainer module user-facing classes

- docs/source/scale/sagemaker.rst
> Add partition command and SageMaker parameters to SageMaker docs

- .github/workflow_scripts/lint_check.sh
- python/graphstorm/__init__.py
> Bump version to 0.3

- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
Add inference support using WholeGraph
> [Wholegraph-feature] Enable inference support using WholeGraph

- python/graphstorm/gconstruct/construct_graph.py
- python/graphstorm/gconstruct/file_io.py
- tests/end2end-tests/data_process/data_gen.py
The data fields we want to read from the input files are the same. We only need to read a data field once.
> Fix a bug in gconstruct

- python/graphstorm/gconstruct/file_io.py
- tests/unit-tests/gconstruct/test_gconstruct_utils.py
> Raise an error when gconstruct reads empty files.

- docs/source/gs-processing/gs-processing-getting-started.rst
- docs/source/index.rst
This PR makes a small change to add gprocess docs into the index page
> [Doc] Modify index page to add gprocessing contents

- python/graphstorm/model/gat_encoder.py
- tests/unit-tests/test_gnn.py
This PR adds a GATEncoder and a test case in test_gnn. 
This PR does not handle 0-in-degree case. As DGL warning, this may lead to invalid results. 
> [Feature] Add gat_encoder

- python/graphstorm/dataloading/dataset.py
- python/graphstorm/gsf.py
- python/graphstorm/model/edge_gnn.py
- python/graphstorm/model/gnn_encoder_base.py
- python/graphstorm/model/node_gnn.py
- python/graphstorm/utils.py
- tests/unit-tests/test_utils.py
> [Wholegraph] Refactor wholegraph inference

- python/graphstorm/model/node_glem.py
*Description of changes:* GLEM LM's forward pass breaks when there are non-textual node features. This PR fixed it by subsetting the node features of seed nodes.
> Bug fix for GLEM LM forward pass with additional node feats

- docs/source/configuration/configuration-run.rst
- python/graphstorm/config/argument.py
- python/graphstorm/dataloading/dataloading.py
- python/graphstorm/dataloading/sampler.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- tests/unit-tests/test_dataloading.py
> Random select the subset of validation set in lp when validation set is huge

- python/graphstorm/model/gat_encoder.py
- tests/unit-tests/test_gnn.py
Currently GAT model does not include self-loop. This PR will automatically add self-loop in the message passing graph.
> Add self-loop in message passing for GAT

- docs/source/tutorials/own-data.rst
- docs/source/tutorials/quick-start.rst
- tools/partition_graph_lp.py
- training_scripts/gsgnn_lp/arxiv_lp.yaml
This PR adds descriptions and commands of Link Prediction in the Quick Start tutorial. To support the change, also modify some code in the partition_graph_lp.py. 
> [Doc] Add LP Command in the Quick Start

- python/graphstorm/data/ogbn_datasets.py
- python/graphstorm/gsf.py
- python/graphstorm/model/gat_encoder.py
- python/graphstorm/model/sage_encoder.py
- tests/unit-tests/data_utils.py
- tests/unit-tests/test_gnn.py
- tools/partition_graph.py
> Change _N and _E to dgl.distributed.constants DEFAULT_NTYPE and DEFAULT_ETYPE

- docs/source/tutorials/own-data.rst
- examples/acm_data.py
- examples/use_your_own_data/acm_lp.yaml
This PR include changes for adding Link Prediction examples into the Use Your Own Graph tutorial
> [Doc] Add Link Prediciton to Use Your Own Graph tutorial

- docker/build_docker_sagemaker.sh
- docker/sagemaker/Dockerfile.sm
- python/graphstorm/sagemaker/sagemaker_partition.py
- sagemaker/launch/launch_partition.py
* Convert the SageMaker partition jobs from training to processing.
* Add Docker login to SM Docker build script
* Add and pin dependencies to SM Docker container
> [SageMaker] Move SageMaker partition job to use SageMaker Processing instead of Training

- graphstorm-processing/docker/0.2.1/sagemaker/Dockerfile.cpu
* Add new SageMaker Dockerfile for v0.2.1
> [GSProcessing] SagMaker Dockerfile for v0.2.1

- docs/source/gs-processing/developer/developer-guide.rst
- docs/source/gs-processing/developer/input-configuration.rst
- docs/source/gs-processing/gs-processing-getting-started.rst
- docs/source/gs-processing/usage/distributed-processing-setup.rst
- graphstorm-processing/docker/0.2.1/sagemaker/Dockerfile.cpu
- graphstorm-processing/docker/build_gsprocessing_image.sh
- graphstorm-processing/docker/push_gsprocessing_image.sh
- graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
- graphstorm-processing/graphstorm_processing/repartition_files.py
- graphstorm-processing/tests/test_dist_heterogenous_loader.py
* Change default behavior when no labels are given, from creating LP masks for all edge types, to creating no masks.
* Fixes to docs formatting.
* Fix broken re-partitioning launch argument.
* Add scipy dependency to SageMaker Dockerfile
* Allow custom tags for image names
> [GSProcessing] Don't produce masks when no labels present, other small fixes

- python/graphstorm/__init__.py
> Version for V0.2.1

- python/graphstorm/data/ogbn_datasets.py
- python/graphstorm/gsf.py
> [Bug Fix] Homogeneous Graph Construction

- python/graphstorm/gconstruct/utils.py
> [Bug Fix] GC for ExtFeatureWrapper

- README.md
This PR adds one line to refer users to our documentations.
> [Doc] Add a doc reference line in README

- docs/source/tutorials/quick-start.rst
> [Doc] Fix doc for Gen-Embedding

- docs/source/scale/sagemaker.rst
This PR modifies the title layers to make some topics, e.g., launch graph partition, and passing addition paramters to SageMaker, more clear.
> [Doc] Modify the SageMaker rst title layers to make things clear

- tests/unit-tests/test_model_save_load.py
This is to fix: https://github.com/awslabs/graphstorm/issues/679.
> [Bugfix] Fix a typo in one of the unit test

- examples/customized_models/HGT/hgt_nc.py
- examples/temporal_graph_learning/main_nc.py
- python/graphstorm/run/gsgnn_dt/distill_gnn.py
- python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- sagemaker/launch/launch_infer.py
As we chain train/inference with node id remapping in the train and inference pipeline, both train/inference entries and remap entry should be more robust to unknown arguments.
Related issue: #674 
Update builtin train/inference entries to accept unknown arguments.
> Update builtin train/inference entries to accept unknown arguments

- .github/workflow_scripts/lint_check.sh
- python/graphstorm/distributed/__init__.py
- python/graphstorm/distributed/primitives.py
- python/graphstorm/model/gnn_encoder_base.py
- python/graphstorm/model/utils.py
- tests/end2end-tests/graphstorm-nc/mgpu_test.sh
When writing data to distributed tensors, we need to flush data to ensure all data have been written to distributed tensors so that we can perform the next operation (e.g., read).
> Add flush operation

- python/graphstorm/model/lm_embed.py
- tests/unit-tests/test_embed.py
The current code cannot load cached LM embeddings correctly.
> Fix a bug in loading cached LM embeddings.

- examples/mag/mag_gnn_lp.yaml
> Update yaml files for running experiments on MAG

- docker/Dockerfile.local
> [Bug Fix] Local Docker Build

- docs/source/gs-processing/developer/input-configuration.rst
- graphstorm-processing/docker/0.2.2/emr-serverless/Dockerfile.cpu
- graphstorm-processing/docker/0.2.2/sagemaker/Dockerfile.cpu
- graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
- graphstorm-processing/graphstorm_processing/config/hf_configs.py
- graphstorm-processing/graphstorm_processing/constants.py
- graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
- graphstorm-processing/pyproject.toml
- graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
- graphstorm-processing/tests/test_converter.py
- graphstorm-processing/tests/test_dist_huggingface_transformation.py
> [GSProcessing] Bert Embedding

- docs/source/configuration/configuration-gconstruction.rst
- docs/source/scale/sagemaker.rst
- docs/source/tutorials/own-data.rst
Align the doc about raw_id_mappings change in this PR: https://github.com/awslabs/graphstorm/pull/641
> [Doc Fix] Sync doc for Remap

- .gitignore
- docs/source/gs-processing/developer/input-configuration.rst
- docs/source/gs-processing/usage/amazon-sagemaker.rst
- docs/source/gs-processing/usage/distributed-processing-setup.rst
- docs/source/gs-processing/usage/emr-serverless.rst
- docs/source/gs-processing/usage/example.rst
- docs/source/gs-processing/usage/row-count-alignment.rst
- graphstorm-processing/docker/README.md
- graphstorm-processing/docker/build_gsprocessing_image.sh
* Some updates and fixes to the docs for 0.2.2
> [GSProcessing] Documentation updates for 0.2.2

- python/graphstorm/gconstruct/utils.py
- tests/unit-tests/gconstruct/test_construct_graph.py
> Fix a bug in balancing training/valid/test in graph partitioning.

- python/graphstorm/gconstruct/utils.py
> [Bug Fix] Fix GConstruct Lint error

- docs/source/advanced/advanced-wholegraph.rst
Update to include the support for learnable embeddings and bert cache.  
> [Doc] Update doc for wholegraph integration

- docs/source/advanced/own-models.rst
- docs/source/install/env-setup.rst
- docs/source/tutorials/own-data.rst
- docs/source/tutorials/quick-start.rst
This PR modifies a few documentations to reflect the changes in v0.2.2 release.
1. Upgrade DGL version to 1.1.3, and add CUDA 12 installation command;
2. Remove all `--ip-config` and `--ssh-port` arguments from training/inference commands;
3. Set all command with `pip` and `python` to unify the Python version.
4. Remove IP address file and SSH related warnings and notes.
> [Doc]Modify Document to reflect the changes in v0.2.2

- graphstorm-processing/pyproject.toml
- setup.py
> [Bug Fix] Fix vulnerability on Pyarrow and Transformer version

- examples/peft_llm_gnn/preprocess_amazon_review.py
> Fix graph data processing script of gpeft example

- docs/source/advanced/own-models.rst
- docs/source/api/graphstorm.rst
- examples/customized_models/HGT/hgt_nc.py
- examples/peft_llm_gnn/main_lp.py
- examples/peft_llm_gnn/main_nc.py
- examples/temporal_graph_learning/main_nc.py
- python/graphstorm/gsf.py
- python/graphstorm/run/gsgnn_dt/distill_gnn.py
- python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- python/graphstorm/utils.py
- tests/end2end-tests/custom-gnn/train.py
> Move setup_device into gs.initialize()

- docker/Dockerfile.local
- python/graphstorm/gpartition/dist_partition_graph.py
> [Partition Image] Add dependency for gs partition

- docs/source/configuration/configuration-gconstruction.rst
- docs/source/tutorials/own-data.rst
- python/graphstorm/gconstruct/file_io.py
- python/graphstorm/gconstruct/transform.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/test_data.py
- tests/unit-tests/gconstruct/test_construct_graph.py
- tests/unit-tests/gconstruct/test_transform.py
> [GConstruct] Add Customized Edge split

- python/graphstorm/gconstruct/remap_result.py
The logging information of remap_result.py is not informative. Add some more info.
> Update logging info of remap result

- docs/source/advanced/own-models.rst
- docs/source/api/graphstorm.eval.rst
- examples/customized_models/HGT/hgt_nc.py
- examples/peft_llm_gnn/main_nc.py
- examples/standalone_mode_demo.ipynb
- examples/temporal_graph_learning/main_nc.py
- python/graphstorm/eval/__init__.py
- python/graphstorm/eval/evaluator.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
- tests/unit-tests/test_dist_eval.py
- tests/unit-tests/test_evaluator.py
- tests/unit-tests/test_inferrer.py
- tests/unit-tests/test_trainer.py
*Issue #757 , if available:*
This PR is the 1st one of a sequence PRs that create new `Evaluator` classes to replace the current `GSgnnInstanceEvaluator`, `GSgnnAccEvaluator`, `GSgnnRegressionEvaluator`, and `GSgnnLPEvaluator`.
This PR create the base `GSgnnBaseEvaluator` to replace the current `GSgnnInstanceEvaluator` and `GSgnnLPEvaluator`, and  the`GSgnnClassificationEvaluator`, which extends from the base and replace the current `GSgnnAccEvaluator`. This PR also replace all occurrence of `GSgnnAccEvaluator` in core code, examples, documents, and tests.
> James c levaluator

- docs/source/tutorials/own-data.rst
- python/graphstorm/gconstruct/file_io.py
- python/graphstorm/gconstruct/transform.py
- tests/unit-tests/gconstruct/test_gconstruct_utils.py
> [GConstruct] Allow parquet file as input for customized edge split

- docs/source/gs-processing/gs-processing-getting-started.rst
- docs/source/gs-processing/usage/distributed-processing-setup.rst
- docs/source/gs-processing/usage/emr-serverless.rst
- graphstorm-processing/docker/0.3.0/emr/Dockerfile.cpu
- graphstorm-processing/docker/build_gsprocessing_image.sh
- graphstorm-processing/docker/push_gsprocessing_image.sh
* Add Dockerfile for EMR on EC2.
* Add instructions in documentation.
* Modify Docker build and push scripts accordingly.
Launched test clusters and jobs using EMR 7.0.0 and 6.10.0.
> [GSProcessing] Add support for EMR on EC2 execution.

- examples/temporal_graph_learning/graphstorm_train_script_nc_config.yaml
- examples/temporal_graph_learning/main_nc.py
The PR fix the yaml config PR of TGAT example code.
> Fix TGAT example

- docs/source/api/graphstorm.dataloading.rst
- examples/customized_models/HGT/README.md
- examples/customized_models/HGT/hgt_nc.py
- examples/peft_llm_gnn/main_lp.py
- examples/peft_llm_gnn/main_nc.py
- examples/temporal_graph_learning/graphstorm_train_script_nc_config.yaml
- examples/temporal_graph_learning/main_nc.py
- python/graphstorm/model/embed.py
- python/graphstorm/model/gat_encoder.py
- python/graphstorm/model/gatv2_encoder.py
- python/graphstorm/model/hgt_encoder.py
- python/graphstorm/model/lm_embed.py
- python/graphstorm/model/rgat_encoder.py
- python/graphstorm/model/rgcn_encoder.py
- python/graphstorm/model/sage_encoder.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- tests/unit-tests/test_dataloading.py
- tests/unit-tests/test_gnn.py
> Update GSgnnData for examples

- docs/source/gs-processing/usage/emr.rst
- docs/source/index.rst
> [Docs] Add documentation for EMR on EC2 for GSProcessing

- docs/source/advanced/own-models.rst
- docs/source/configuration/configuration-run.rst
- docs/source/install/env-setup.rst
This PR fixed a few typo errors in documentation.
> [Doc] Minor doc fix

- tests/end2end-tests/create_data.sh
- tests/end2end-tests/data_gen/movielens_multi_task.json
- tests/end2end-tests/data_gen/process_movielens.py
- training_scripts/gsgnn_mt/README.md
- training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml
#789 
Add multi-task learning test dataset based on movielens.
> [Multi-task Learning] Add Multi-task test dataset

- docs/source/notebooks/Notebook_0_Data_Prepare.ipynb
This PR updates the example Notebook 0 to reflect the changes of output folder structure of graph construction in v0.3.
> [Doc] Update the Notebook 0 to reflect the changes in v0.3

- graphstorm-processing/docker/push_gsprocessing_image.sh
* Fix the flag letter for architecture during GSP image push
> [GSProcessing] Fix arg parsing error in push_gsprocessing_image

- .github/workflow_scripts/e2e_mgpu_check.sh
> [Bug Fix] Fix the wholegraph version

- docs/source/configuration/configuration-gconstruction.rst
This PR update the gconstruction documents, clarifying the explanation of the two boolean arguments.
> [Doc] Update gconstruct configuration doc to clarify the usage of two boolean arguments

- docs/source/index.rst
> Add multi-task learning doc in the doc page

- docs/source/advanced/multi-task-learning.rst
- docs/source/index.rst
> Fix doc examples

- .github/workflow_scripts/e2e_mgpu_multitask_check.sh
- .github/workflows/continuous-integration.yml
Please check the test result after modifying the workflow: https://github.com/jalencato/graphstorm/actions/runs/9685005447
> [CI] [Holding for Test] Separate Multitask for a new CI workflow

- python/graphstorm/run/gsgnn_dt/distill_gnn.py
- python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
- python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
- python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
- python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
- python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
- python/graphstorm/run/gsgnn_mt/mt_infer_gnn.py
- python/graphstorm/run/gsgnn_np/gsgnn_np.py
- python/graphstorm/run/gsgnn_np/np_infer_gnn.py
#799 
Add Warnings for unknown arguments. 
> Print unknown arguments when executing GraphStorm command-lines.

- .github/workflow_scripts/e2e_mgpu_check.sh
- .github/workflow_scripts/e2e_mgpu_multitask_check.sh
> [CI] Ci profiling on lp + multitask

- python/graphstorm/gconstruct/remap_result.py
- tests/end2end-tests/check_infer.py
- tests/end2end-tests/create_data.sh
- tests/end2end-tests/data_gen/process_movielens.py
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
#785
The end2end test does not cover the ID remapping after link prediction training use case.
Add some tests to cover the use cases.
> Add some test for testing ID remapping after link prediction training

- python/graphstorm/gconstruct/transform.py
Most of error reports of feature transformations do not provide the information of the name of the feature having issues.
Optimize the error reports.
> Add feature name in the error reports of feature transformations.

- docs/source/api/notebooks/index.rst
This PR fix the error in the http link of `demo_models.py` file in the notebook index page.
> [Doc] Fix `demo_models.py` link

- python/graphstorm/model/gnn.py
This PR remove the two assertions of using edge features and edge input encoder to enable experimental edge feature support.
> [Enhancement] Enable edge feature and edge input encoder for experimental edage feature support

- tools/graph_sanity_check.py
> Make warning information of graph_sanity_check.py more informative.

- README.md
- python/graphstorm/__init__.py
> [Doc] Update Doc to V0.3.1

- docs/source/advanced/link-prediction.rst
https://github.com/awslabs/graphstorm/issues/823
> Update doc for hard negative

- python/graphstorm/config/argument.py
``--return-proba `` argument does not take effect on config.return_proba.
Fix the bug
> [Bugfix] Fix --return-proba argument

- docs/source/cli/model-training-inference/output-remapping.rst
- docs/source/cli/model-training-inference/output.rst
> [Doc] Doc for Node ID remapping.

- python/graphstorm/config/__init__.py
- python/graphstorm/config/config.py
- python/graphstorm/eval/utils.py
- python/graphstorm/gsf.py
- python/graphstorm/inference/lp_infer.py
- python/graphstorm/model/__init__.py
- python/graphstorm/model/edge_decoder.py
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
- tests/end2end-tests/graphstorm-lp/test.sh
- tests/unit-tests/test_decoder.py
#980 
Add RotatE score function for link prediction.
> Add support of RotatE for link prediction.

- docs/source/advanced/link-prediction.rst
- docs/source/api/references/graphstorm.model.rst
- docs/source/cli/model-training-inference/configuration-run.rst
- python/graphstorm/eval/utils.py
- python/graphstorm/model/edge_decoder.py
> [Doc] Add doc for RotatE

- docs/source/advanced/gsprocessing-emr-ec2.rst
- docs/source/cli/graph-construction/distributed/gsprocessing/aws-infra/emr.rst
- docs/source/index.rst
Preview Page on read the doc: https://jalencato-graphstorm-doc.readthedocs.io/en/emr_ec2_doc/advanced/gsprocessing-emr-ec2.html
> [Doc] Add back GSProcessing EMR EC2 document for spark-submit

- docs/source/api/notebooks/Notebook_1_NC_Pipeline.ipynb
- docs/source/api/notebooks/Notebook_2_LP_Pipeline.ipynb
- docs/source/api/notebooks/Notebook_3_Model_Variants.ipynb
- docs/source/api/notebooks/Notebook_4_Customized_Models.ipynb
This PR fixes one typos of "Prerequsites"
> [Doc] Fix Notebooks' typos

- tests/end2end-tests/data_process/data_gen.py
> [CI] Remove hard-coded bert model cache

- README.md
> [Readme] Update Doc to highlight DGL version support

- graphstorm-processing/docker/0.4/emr-serverless/Dockerfile.cpu
- graphstorm-processing/docker/0.4/emr/Dockerfile.cpu
- graphstorm-processing/docker/0.4/sagemaker/Dockerfile.cpu
- graphstorm-processing/pyproject.toml
- python/graphstorm/__init__.py
* Update GSF main repo version number
* Update GSProcessing v0.4 in config and dockerfile
> [Version] Update main repo version to V0.4

- python/graphstorm/config/argument.py
- tests/unit-tests/test_config.py
When the first fanout of the fanout list is -1, the program will fail.
Fix the bug
> [Bugfix] Fix the bug when the first fanout of the fanout list is -1

- docs/source/advanced/using-graphbolt.rst
- docs/source/cli/graph-construction/distributed/gspartition/ec2-clusters.rst
- docs/source/cli/graph-construction/single-machine-gconstruct.rst
- docs/source/cli/model-training-inference/configuration-run.rst
- docs/source/index.rst
- docs/source/tutorials/own-data.rst
> [GraphBolt] Add example for using GraphBolt

- .github/workflows/continuous-integration.yml
> [Ci] Update CI timeout for e2e test

- python/graphstorm/model/edge_decoder.py
Add `versionadded` annotations for RotatE and TransE.
> [Doc] Add annotations for RotatE and TransE.

- docs/source/api/references/graphstorm.eval.rst
- python/graphstorm/eval/evaluator.py
- python/graphstorm/model/edge_decoder.py
Add docs for the newly created generic LP evaluators.
> [Doc] Add docs for LP evaluators.

- docs/source/api/references/graphstorm.model.rst
- docs/source/api/references/index.rst
- python/graphstorm/model/__init__.py
- python/graphstorm/model/loss_func.py
#1004
Add documentation for loss functions.
> [Documentation] Documentation for loss functions.

- tests/end2end-tests/data_process/gen_multi_task_remap_test.py
- tests/end2end-tests/graphstorm-mt/mgpu_test.sh
- tests/unit-tests/test_trainer.py
Update both unit tests and end2end tests to add more tests for edge feature reconstruction.
> Add more tests for edge feature reconstruction.

- tests/end2end-tests/data_process/gen_multi_task_remap_test.py
> [Bugfix] Fix CI pipeline error caused by merging #1059

- tests/unit-tests/gconstruct/test_transform.py
* Try to fix flaky test by reducing required accuracy
> Fix flaky `test_fp_min_max_transform` test.

- .github/workflow_scripts/lint_check.sh
- python/graphstorm/gsf.py
* Previously our lint check did not include top-level files under graphstorm/, this PR fixes that.
> Add gsf.py to lint checks and fix linting errors in file.

- docs/source/install/env-setup.rst
> [Doc Fix] Update Docker Container setup in Doc

- python/graphstorm/gconstruct/file_io.py
> [Enhancement] Add sort to filename wildcard extension for GConstruct

- docs/source/advanced/link-prediction.rst
- docs/source/cli/model-training-inference/configuration-run.rst
- python/graphstorm/eval/evaluator.py
- python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
- python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
* Add rst docs for AMRI and other LP eval metrics
> Add documentation for AMRI and other LP eval metrics

- docs/source/cli/notebooks/Notebook_4_MT_CLI.ipynb
- examples/use_your_own_data/acm_mt.yaml
Add yaml configuration file for model training
> [Documentation] Add multi-task learning CLI notebook example

- docs/source/cli/model-training-inference/distributed/sagemaker.rst
> [Doc] gs_gen_node_embedding task command tutorial for SageMaker

- python/graphstorm/model/utils.py
- tests/unit-tests/test_model_save_load.py
Add unit tests for load_sparse_emb and save_sparse_emb
> Add unit tests for load_sparse_emb and save_sparse_emb

- docs/source/cli/graph-construction/single-machine-gconstruct.rst
- python/graphstorm/gconstruct/transform.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/test_data.py
- tests/unit-tests/gconstruct/test_construct_graph.py
- tests/unit-tests/gconstruct/test_transform.py
#1093 
Add standard transformation for gconstruct.
> Add standard transform for gconstruct

- docs/source/advanced/language-models.rst
- docs/source/tutorials/own-data.rst
- docs/source/tutorials/quick-start.rst
#1027 
This PR modifies the path of GraphStorm artifacts, e.g., examples, scripts, and configuration files, to be relative paths to the root path of GraphStorm source code.
> [Document] Handle Issue #1027

- examples/network_traffic_prediction/Synthetic_Airport_Traffic_wAirlines.ipynb
This PR fixes the JSON format error.
> [Bug] Fix Notebook JSON Format Error in AirTrans Example

- python/graphstorm/data/ogbn_datasets.py
> Fix lint error in python/graphstorm/data/ogbn_datasets.py

- .github/workflows/semgrep.yml
> [CI] Update Github workflow for Semgrep version after 2.103.0

- setup.py
https://github.com/awslabs/graphstorm/issues/988
Follow #1144 to update graphstorm dependency.
> Add an optional requirement of tensorboard package in graphstorm dependency

- python/graphstorm/dataloading/dataset.py
- training_scripts/gsgnn_np/papers100M_nc.yaml
> Update train config for papers100M to include features, make missing feature message more descriptive.

- examples/sagemaker-pipelines-graphbolt/README.md
Editing readme for consistency across commands.
> [Examples] Editing readme

- python/graphstorm/inference/emb_infer.py
- python/graphstorm/model/gnn.py
- python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
- tests/end2end-tests/graphstorm-ec/mgpu_test.sh
- tests/end2end-tests/graphstorm-er/test.sh
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
- tests/end2end-tests/graphstorm-mt/mgpu_test.sh
- tests/end2end-tests/graphstorm-nc/mgpu_test.sh
> Save relation_embeddings for models trained with link prediction in gs_gen_node_embedding

- examples/sagemaker-pipelines-graphbolt/README.md
- examples/sagemaker-pipelines-graphbolt/deploy_arxiv_pipeline.sh
- examples/sagemaker-pipelines-graphbolt/deploy_papers100M_pipeline.sh
Revising readme, changing image names, fix typo.
> [Examples] Revise GS-GB-SM example

- docs/source/cli/model-training-inference/distributed/sagemaker.rst
Add space to render the command correctly.
> [Doc] Fix doc for launching Embedding Task

- tests/unit-tests/test_nn_model.py
- tests/unit-tests/test_trainer.py
Adding tests for HGTLayerwithEdgeFeat module.
> [Tests] HGTLayerwithEdgeFeat tests

- python/graphstorm/model/hgt_encoder.py
- tests/unit-tests/test_nn_encoder.py
> [Tests] HGTEncoder tests

- python/graphstorm/data/constants.py
- python/graphstorm/gconstruct/id_map.py
- tests/unit-tests/gconstruct/test_remap_result.py
* Fixes writing behavior and adds corresponding unit test
* GenAI used to extend new unit test
Fixes #1177 
> Fix overlapping IDs being written when ID map writes to multiple files

- docs/source/install/env-setup.rst
This PR fixes the CPU installation string format.
> [Doc] Fix cpu installation string format

- docs/source/install/env-setup.rst
> [Doc] Fix doc links

- python/graphstorm/gconstruct/utils.py
- tests/unit-tests/gconstruct/test_construct_graph.py
#1205 
Add unit test for Issue 1205 and fix the bug.
> [Bug Fix] Fix the case when input graph is a homogeneous graph without any mask, gconstruct will fail.

- python/graphstorm/__init__.py
> Bump version to 0.4.1 in __init__.py

- sagemaker/launch/launch_infer.py
Fix bug in sagemaker launch script for when loading use-graphbolt argument.
> [Bug] Sagemaker Launch Script fix for Inference

- setup.py
> [Dependencies] Add torchdata and pydantic dependencies for GraphStorm

- docs/source/advanced/sagemaker-pipelines.rst
> Add missing note to SM pipelines docs

- examples/customized_models/HGT/README.md
- examples/customized_models/HGT/hgt_nc.py
Updating the HGT Custom model example for consistency and newer version of dgl.
> [Examples] Updating Customized Model/HGT Example

- docs/source/cli/graph-construction/single-machine-gconstruct.rst
- graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
- python/graphstorm/__init__.py
- python/graphstorm/gconstruct/transform.py
- tests/unit-tests/gconstruct/test_construct_graph.py
* Apply final comments from #1225 
* Also change test names for other transformations. Previously all transformations were tested under a single unit test. This meant that if one of the tests failed the following ones would not run which is not the intended behavior when testing, we don't want tests to depend on each other. This also allows the individual tests to be discoverable and testable within an IDE.
* Also fixes a pylint error that was introduced in #1227 
> Apply suggestions for Noop transformation

- docs/source/index.rst
> [Docs] Add missing link to SM Pipelines doc

- docs/source/index.rst
> [Docs] Add missing link to SM Pipelines doc (#1232)

- docs/source/advanced/imbalanced-labels.rst
- docs/source/cli/model-training-inference/configuration-run.rst
- graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
- graphstorm-processing/tests/test_dist_label_loader.py
- python/graphstorm/gpartition/random_partition.py
- python/graphstorm/gsf.py
- python/graphstorm/model/loss_func.py
- python/graphstorm/trainer/ep_trainer.py
- python/graphstorm/trainer/np_trainer.py
- tests/end2end-tests/graphstorm-ec/test.sh
- tests/end2end-tests/graphstorm-nc/test.sh
- tests/unit-tests/gpartition/conftest.py
- tests/unit-tests/gpartition/test_random_partition.py
- tests/unit-tests/test_gsf.py
* Previously it was possible for random partition to create assignments that led to some node types having 0 nodes in one partition. This would eventually trigger errors in DistPart.
* Similarly, we allowed the creation of partitions for node types with fewer nodes that the requested partitions.
* This PR ensures every partition will have at least one node, and raises an error if we try to create a partition for a node type with fewer nodes than the requested partitions.
* Expand tests to cover all cases.
> [GSPartition] Ensure random partition assigns at least one node per partition

- docs/source/cli/model-training-inference/distributed/sagemaker.rst
- sagemaker/launch/launch_hyperparameter_tuning.py
Fixes #1243
* Add support for HyperBand HPO by allowing the jobs to pick up metrics during training instead of just at the end of a job.
* Add `--hb-min-epochs` and `--hb-max-epochs` parameters to HPO launcher, with default values to maintain backwards compatibility
* 
> [SageMaker] Support HyperBand optimization strategy

- python/graphstorm/config/argument.py
- python/graphstorm/gsf.py
- tests/unit-tests/test_config.py
- tests/unit-tests/test_gsf.py
Fixes #1237 
Add more checks for num_classes.
> [Fix Bug] Fix the bug of setting num_classes to 1 does not trigger an error for cross entropy

- tests/unit-tests/test_hfbert.py
> [CI] Reduce the LM model candidate

- python/graphstorm/gconstruct/construct_graph.py
- tests/end2end-tests/data_process/data_gen.py
- tests/end2end-tests/data_process/test_data.py
- tests/unit-tests/gconstruct/test_construct_graph.py
#42 
For node types that do not have features, it is not necessarily to ask users to provide node files.
> [GConstruct] Allow featureless nodes to not have node files

- .gitignore
- README.md
Fixes https://github.com/awslabs/graphstorm/issues/1262
* Add status badges
* Align quick start examples with main documentation, simplify/condense instructions
* Add blog post links
* Remove outdated information/commands
* Recommend using SageMaker AI for easier distributed training
* Add build/ and dist/ directories to .gitignore
> [Documentation] Re-structure and update README

- python/graphstorm/dataloading/dataset.py
* Previously when running all-nodes inference we got logs like: `INFO:root:Transaction does not contains We will do inference on the entire node set.`
* This PR fixes the logging and improves the function logging.
* Since this does not change functional code we can ensure it doesn't change library functionality. We'll still run CI though
> Small improvements to logs + docstring for dataloading.dataset.get_node_infer_set

- docs/source/cli/graph-construction/distributed/gsprocessing/distributed-processing-setup.rst
- graphstorm-processing/docker/build_gsprocessing_image.sh
- graphstorm-processing/docker/push_gsprocessing_image.sh
Fix GSProcessing docker push script:
* Add version validation for both build&push script.
* Fix the region issues, now users can either set up the aws config region or pass the region as an argument with `-r`.
> [GSProcessing] Fix docker script&doc

- python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
- tests/end2end-tests/graphstorm-lp/mgpu_test.sh
This PR allows users to pass the config `fixed-test-size` for training a LM with link prediction.
> [Feature] Enable the Config "fixed-test-size" for LM training with Link Prediction.

- graphstorm-processing/docker/0.5.0/emr-serverless/Dockerfile.cpu
> [GSProcessing] Fix Spark Base Image
