python/graphstorm/config/argument.py
python/graphstorm/trainer/ep_trainer.py
python/graphstorm/trainer/lp_trainer.py
python/graphstorm/trainer/np_trainer.py
tests/end2end-tests/graphstorm-er/test.sh
tests/unit-tests/test_config.py
tests/unit-tests/test_evaluator.py

When both save_model_per_iters and evaluation_frequency are set to the same value, save_topk actually does not save the best model according to the evaluation, as there is a mismatch in its way of counting the iterations.
This PR fixes that bug.

[BugFix] save_topk does save the right model after evaluation.

---

inference_scripts/lp_infer/lp_infer_gnn.py
inference_scripts/lp_infer/lp_infer_lm.py

*Issue #57,:*
The LP inference script use "num_negative_edges" for test evaluation, but it should use "num_negative_edges_eval" same as the trainer scripts.
After fix this bug, the MRR values of trainer and infer are similar.

[Fix] fix a bug: using the num_negative_edges for test evaluation when do inference

---

.github/workflow_scripts/e2e_check.sh
.github/workflow_scripts/e2e_mgpu_check.sh
tests/end2end-tests/graphstorm-ec/mgpu_test.sh
tests/end2end-tests/graphstorm-ec/test.sh
tests/end2end-tests/graphstorm-er/mgpu_test.sh
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh

If the output of training launch script is redirected to a file through `tee` command, the error code got from `$?` is from tee instead of the training script. We need to get the error code through `${PIPESTATUS[0]}`.
Change integration test code to use `${PIPESTATUS[0]}` instead of `$?`

[Bug Fix] Fix error code check of CI script

---

python/graphstorm/config/argument.py
tests/unit-tests/test_config.py

By default save_model_per_iters is set to -1 which means GFS will not save models within an epoch. In this case, evaluation_frequency should be able to use any positive integer.
#20 
Fix the bug

BugFix: evaluation_frequency needs to work with save_model_per_iters set to -1

---

python/graphstorm/model/utils.py

Create the save_perf_results_path if it is not existed.
Create the save_perf_results_path if it is not existed to prevent json dump no file or directory error.

Update utils.py to prevent json dump no file or directory error

---

sagemaker/launch/launch_infer.py
sagemaker/launch/launch_train.py

We remove the import of the graphstorm module, allowing the scripts to be ran from a Python environment that doesn't have GraphStorm installed.
Small re-arrangement of the imports to match PEP8 guidelines.

Remove GSF dependency from SageMaker launch scripts.

---

python/graphstorm/config/argument.py
python/graphstorm/model/node_decoder.py

Node regression tasks with --return-proba flag will crash.
Add predict_proba in EntityRegression

[Bug Fix] Fix EntityRegression with --return-proba

---

python/graphstorm/gconstruct/construct_graph.py
python/graphstorm/gconstruct/id_map.py
tests/unit-tests/test_construct_graph.py

We cannot convert the ID map to numpy arrays first. Numpy arrays consume a large amount of memory to store a large string array.

change the way of saving ID map.

---

python/graphstorm/gconstruct/construct_graph.py
tests/end2end-tests/data_process/data_gen.py
tests/end2end-tests/data_process/test_data.py

When no node feature is provided for a node type, the process_node_data will fail

Fix a bug of parse_node_feature

---

python/graphstorm/eval/eval_func.py
tests/unit-tests/test_eval_func.py

When dtype of predict and label does not match, compute_mse and compute_rmse will crash

Fix the case when dtype of predict and label does not match in regression tasks.

---

tests/end2end-tests/data_process/data_gen.py

Use cached BERT model in CI-docker image to do testing instead of downloading it

---

python/graphstorm/model/gnn_encoder_base.py
python/graphstorm/utils.py

Using tqdm in dist_inference will cause `deadlock` (barrier timeout) on large graph link prediction inference. 
Remove tqdm.

Remove tqdm in dist_inference

---

docker/Dockerfile.local

11.3.0 does not seem to be supported anymore.
https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md

Updating CUDA  docker image tag to 11.3.1

---

python/graphstorm/dataloading/dataloading.py

DGL package does not have `dgl.dataloading.FastMultiLayerNeighborSampler` 
I am sure if this is a typo? Maybe we should change it to `dgl.dataloading.MultiLayerNeighborSampler`?

`FastMultiLayerNeighborSampler` not in `dgl.dataloading`

---

python/graphstorm/sagemaker/sagemaker_infer.py
python/graphstorm/sagemaker/sagemaker_train.py

Commit 32c2baa995e331db1bfff574ddd0de2dae20816e tries to remove the trained model or generated node embeddings under /opt/ml/model/ and /opt/ml/checkpoints/ to avoid uploading the trained model or node embeddings using SageMaker default model saving mechanism which is slow. However, this may trigger the "Device or resource busy: '/opt/ml/model'" error.
In this PR, we change the training/inference output path to /opt/ml/gsgnn_model/ and /opt/ml/infer_output respectively to avoid the above problem.

Fix Device or resource busy: '/opt/ml/model' bug when running SageMaker training and inference

---

python/graphstorm/run/launch.py
python/graphstorm/sagemaker/sagemaker_infer.py
python/graphstorm/sagemaker/sagemaker_train.py

By default, python processes buffer stdout and stderr streams. When a trainer or server crashes, the buffered prints will be lost. This makes debugging distributed training/inference difficult.
Use python -u option to force stdout and stderr streams to be unbuffered.

Use python -u option to force stdout and stderr streams to be unbuffered

---

python/graphstorm/sagemaker/utils.py

There is a logic error in [python/graphstorm/sagemaker/utils.py:L251](https://github.com/awslabs/graphstorm/pull/332/files#diff-3bd5dedc90be6c0508ab83d0a94ed14e7dfd5857db7eeb9eb32ea4aed46fdeb5). The graph_config will always be "metadata.json", which actually is no longer used. The actual graph_config name should be f"{graph_name}.json"

Fix wrong graph partition config filename bug

---

python/graphstorm/gconstruct/utils.py
tests/unit-tests/gconstruct/test_gconstruct_utils.py

If a worker process fails, the entire graph construction pipeline will hang. If a worker fails, we should fail the entire graph construction pipeline immediately.

Handle errors in the worker processes in the graph construction pipeline

---

examples/customized_models/HGT/hgt_nc.py
tools/kill_cleanup_disttrain.sh

Fix two errors:
- hgt_nc.py uses gs.get_rank(), which should be config.local_rank for multiple instances.
- kill_cleanup.sh, should have a white space in line 15.

[Fix] fix hgt get_rank error and cleanup script typo

---

python/graphstorm/gconstruct/transform.py
tests/unit-tests/gconstruct/test_construct_graph.py

Allow out_dtype int8 to support user defined train_mask, val_mask and test_mask

---

.github/workflows/continuous-integration.yml

This PR is to increase the timeout assumed by the CI IAM roles.
This increase the timeout of any long tests running in the CI from 1 hour to 4 hours.

Increasing IAM role token expiry timeout

---

docker/build_docker_sagemaker.sh
docker/sagemaker/Dockerfile.sm

* We clone a more recent version of DGL on to the image, that includes changes needed to run partitioning on SageMaker.
* We clean up temporary cache files after pip/apt installations, as listed in [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get). This reduces image size by ~300MB.
* Enable [buildkit](https://docs.docker.com/build/buildkit/) if available for builds. This will avoid pulling both CPU and GPU images among other optimizations.

[SageMaker][Docker] Clone more recent DGL code, remove cache files, use Buildkit.

---

python/graphstorm/model/utils.py
tests/unit-tests/test_utils.py

This PR fixes the previous node ID mapping logic. Not use the node_mapping.pt node IDs to map back, but use the index of node IDs to map back.

[Fix] Fix node id mapping back logic

---

tests/end2end-tests/graphstorm-ec/mgpu_test.sh
tests/end2end-tests/graphstorm-ec/test.sh
tests/end2end-tests/graphstorm-er/test.sh
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-lp/test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/test.sh

Using `error_and_exit ${PIPESTATUS[0]}` to capture the error status of testing scripts that do not redirect outputs using pipe is not correct.

Fix CI end2end test

---

python/graphstorm/gconstruct/transform.py
tests/unit-tests/gconstruct/test_transform.py

An error happens when the loaded categorical features include both integers and strings. This may happen when loading features from CSV files.

Fix categorical transform

---

python/graphstorm/model/lm_embed.py
tests/unit-tests/data_utils.py
tests/unit-tests/test_embed.py
tests/unit-tests/test_gnn.py

The original code locates a BERT model based on the index. There is potentially a bug here. If a user fine-tune BERT models on two node types:
```
node_lm_models:
-
lm_type: bert
model_name: "bert-base-uncased"
gradient_checkpoint: true
node_types:
- paper
-
lm_type: bert
model_name: "bert-base-uncased"
gradient_checkpoint: true
node_types:
- fos
```
If the user trains the GNN model with the following config,
```
node_lm_models:
-
lm_type: bert
model_name: "bert-base-uncased"
gradient_checkpoint: true
node_types:
- fos
-
lm_type: bert
model_name: "bert-base-uncased"
gradient_checkpoint: true
node_types:
- paper
```
The original code will use the wrong BERT model for the node types.
The fix is to associate the BERT model with node types and the parameter names …

Refactor the code of BERT computation to fix a potential bug.

---

tools/README.md
tools/gen_ogb_dataset.py

I found that:
- `gen_ogb_dataset.py` uses argument name `bert_model_name` to initialize `OGBTextFeatDataset` object. It was changed to `lm_model_name` in #386.
- `partition_graph.py` takes `--lm-model-name` argument instead of `--bert-name`.

Updated arguments names

---

python/graphstorm/config/argument.py
tests/unit-tests/test_config.py

If our task is binary classification and evaluate by precision-recall, we might need to set `num_classes = 1` and `multilabel=true`.
We may not want to set `num_classes = 2` and `multilabel=false` for this case because precision-recall is computed on the positive class.

argument num_classess > 0 instead of > 1

---

python/graphstorm/model/rgcn_encoder.py

It is possible that the number of destination nodes is 0. The code will trigger the assert even though the input data are correct.

Fix a bug in RGCN encoder

---

python/graphstorm/gconstruct/transform.py
tests/unit-tests/gconstruct/test_transform.py

For CategoricalTransform, when it is doing transformation given a pre-defined mapping table, it is possible that, the new graph data have some unknown categories. This PR will ignore these unknown categories and set the corresponding feature as all zeros. 

Fix the case when some categories do not exist in transform_conf

---

graphstorm-processing/graphstorm_processing/distributed_executor.py

* Improve the way we handle unknown config versions with more descriptive messages and fall-back parsing.
* If a version name is not recognized we'll first try to parse the file as GConstruct. If that fails we assume GSProcessing input.

[GSProcessing] Improve handling of configs with unknown version.

---

python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_np/np_infer_gnn.py

In the GNN inference with BERT models, we first cache the BERT embeddings and then cache the embeddings from the input layer. This causes a lot of unnecessary memory consumption. An easy to avoid this is to remove caching the BERT embeddings in the inference script.

Fix the problem of caching twice

---

graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/graphstorm_processing/repartition_files.py
graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
graphstorm-processing/tests/test_dist_heterogenous_loader.py
graphstorm-processing/tests/test_repartition_files.py

* We use `dst:relation-rev:src`  for reverse edge names instead of `dst:rev-relation:src` to match GConstruct.
*Testing*:
* pytest and test job (with re-partition follow-up) succeed

[GSProcessing] Name reverse edges as `dst:relation-rev:src` 

---

.github/workflow_scripts/lint_check.sh

`python3 -m pip install --upgrade prospector pip` has a change to install astroid==3.0 (do not know why) which is not compatible with lint.
Fix astroid version to 2.15.7 in this PR.

Fix lint does not work with astroid==3.0 error.

---

graphstorm-processing/docs/Makefile
graphstorm-processing/docs/make.bat
graphstorm-processing/docs/source/conf.py
graphstorm-processing/docs/source/developer/developer-guide.rst
graphstorm-processing/docs/source/developer/input-configuration.rst
graphstorm-processing/docs/source/index.rst
graphstorm-processing/docs/source/usage/amazon-sagemaker.rst
graphstorm-processing/docs/source/usage/distributed-processing-setup.rst
graphstorm-processing/docs/source/usage/example.rst

[GSProcessing] Add documentation

---

examples/customized_models/HGT/hgt_nc.py

This PR fixed the naming error in the HGT example python file, using the new `GSgnnNodePredictionInferrer` class name.

[Bug Fix] Fix HGT example's infer to inferrer

---

python/graphstorm/model/hgt_encoder.py

This PR fixed the error when no edge exists in a block, but the relation type still exist.
The previous code assign `edge_fn` to all relation types in a mini-batch. But some mini-batchs could have the case where there is no edge for a specific relation type. In such case, the that relation type has an `edge_fn`, but no nodes and edges. When call `multi_update_all()` function, that relation type will fail due to no node or edge data.
The new implementation will filter up such no-edge relation type, and only assign `edge_fn` to relation types having edges. Therefore fix this issue.

[Bug fix]Fix hgt_encoder no edge error

---

CONTRIBUTORS.md
README.md
docker/README.md
docs/source/install/env-setup.rst
docs/source/scale/distributed.rst

This PR fixes some small issues in the instructions on how to setup a (distributed) environment for GraphStorm. It: 
- changes some links so that they point to GraphStorm's docs instead of to deprecated wiki,
- changes/adds some links so that they point to more accurate parts of the instruction,
- adds the tip how to avoid having to preface all Docker commands with _sudo_ (which is the case by default on some AWS instances),
- adds _-o StrictHostKeyChecking=no_ flag for checking the connectivity between containers (which is also used for connecting in _python/graphstorm/run/launch.py_ file and without which it seems impossible to connect following the current instruction),
- adds a step of exchanging the ssh keys between Docker containers
By submitting this pull request, I confirm that …

[Doc] Improving instruction for a distributed setting

---

.github/workflow_scripts/lint_check.sh
python/graphstorm/model/utils.py
tests/end2end-tests/check_infer.py
tests/unit-tests/test_utils.py

Change the way how node embeddings are saved
From
PATH_TO_EMB:
|- emb_info.json
|- ntype0_emb.part00000.bin
|- ...
|- ntype1_emb.part00000.bin
|- ...
To
PATH_TO_EMB:
|- emb_info.json
|- ntype0
|- emb.part00000.bin
|- emb.part00001.bin
|- ...
|- ntype1
|- emb.part00000.bin
#508 

Change the way how node embeddings are saved

---

docs/source/configuration/configuration-run.rst

This PR fix the documentation of `return_proba`:
- Add the return_proba argument;
- Add a note on eval_metric.

[Doc] Add return_proba argument explanation

---

docs/source/configuration/configuration-run.rst

The previous configuration of training and inference has the bolding font issue. This PR fix this issue by adding a space line after each argument description.

[Doc] Fix bolding font format error in the configuration-run rst file

---

python/graphstorm/model/hgt_encoder.py
python/graphstorm/model/rgat_encoder.py
tests/unit-tests/test_nn_model.py

When inputs of RGAT.RelationalAttLayer have some node types with input shape (0, x). The module will crash.
Fix the bug. More details please see tests/unit-tests/test_nn_model.py: test_rgat_with_zero_input

[Bug Fix] Fix RGAT when inputs of rgat.forward have shape (0, x)

---

python/graphstorm/gconstruct/construct_graph.py
python/graphstorm/gconstruct/id_map.py
tests/unit-tests/gconstruct/test_construct_graph.py

The logic of skipping edges with missing src or dst nodes in ID mapping will fail when there are edge features.

Fix the bug when there are edges with missing src or dst nodes, the num edge features != num edges

---

python/graphstorm/dataloading/dataloading.py
python/graphstorm/model/edge_gnn.py
python/graphstorm/model/gnn_encoder_base.py
python/graphstorm/model/node_gnn.py
tests/unit-tests/test_dataloading.py

Previously in dist_inference_one_layer, node_mini_batch_gnn_predict, dist_minibatch_inference, edge_mini_batch_gnn_predict, we use len(list(dataloader)) to get the length of a dataload which is costy. Change the implementation to use len(datalaoder)

Update the way of getting length of dataloader

---

python/graphstorm/model/lm_embed.py
python/graphstorm/model/utils.py
python/graphstorm/utils.py
tests/unit-tests/test_embed.py

Now the embeddings saved by save_pytorch_embeddings are saved as per node type.
This PR fixes the path issue of load cached LM embeddings.

Fix load embeding

---

python/graphstorm/dataloading/dataloading.py

When sampling more neighbors to construct node features, we should run this in the sampling process instead of in the trainer process.

Speed up sampling for constructing node features.

---

docs/source/gs-processing/developer/input-configuration.rst
docs/source/index.rst
graphstorm-processing/graphstorm_processing/config/config_conversion/converter_base.py
graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
graphstorm-processing/graphstorm_processing/config/config_parser.py
graphstorm-processing/graphstorm_processing/config/feature_config_base.py
graphstorm-processing/graphstorm_processing/config/numerical_configs.py
graphstorm-processing/graphstorm_processing/constants.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/__init__.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json
graphstorm-processing/tests/test_converter.py
graphstorm-processing/tests/test_dist_heterogenous_loader.py
graphstorm-processing/tests/test_dist_label_loader.py
graphstorm-processing/tests/test_dist_numerical_transformation.py

Closes #572 
* Adds a single-column and multi-column numerical transformations.
* We support missing data imputation, and value normalization.
* For missing data we support `mean`, `median` and `most_frequent` imputation.
* For normalization we support `mix-max` and `standard` which divides all values
by their column sum.
* We update the GConstruct config converter to allow pass-through of the min-max transformation.
* We change the GSProcessing feature config key that describes the transformation from `transform` to `transformation`.

[GSProcessing] Add support for numerical and multi-numerical transformations.

---

python/graphstorm/dataloading/__init__.py
python/graphstorm/dataloading/dataloading.py
python/graphstorm/dataloading/sampler.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
tests/unit-tests/test_dataloading.py

In addition to sharing negatives in the joint negative sampler, we add more negatives by using in-batch negatives.

Add support in-batch joint negative

---

python/graphstorm/gconstruct/file_io.py
tests/unit-tests/gconstruct/test_gconstruct_utils.py

When wildcard is used to specify edge files while there is no file matching, gconstruct does not report the error as early as possible.

[Bug fix] Fix the error report when the input dir is empty

---

docs/source/gs-processing/usage/amazon-sagemaker.rst
docs/source/gs-processing/usage/emr-serverless.rst
docs/source/gs-processing/usage/example.rst
docs/source/gs-processing/usage/row-count-alignment.rst
graphstorm-processing/graphstorm_processing/repartition_files.py
graphstorm-processing/scripts/run_repartitioning.py
graphstorm-processing/tests/test_repartition_files.py

Also add more detailed docs about re-partitioning step.
* We use thread-parallelism for in-memory file repartition to speed up the process. In our experiments with 10B+ edges, we observe at least 2x speedup.
* Add more detailed documentation about the re-partitioning step, what it does and why.

[GSProcessing] Add thread-parallelism to in-memory repartition implementation.

---

docs/source/gs-processing/usage/amazon-sagemaker.rst
docs/source/gs-processing/usage/distributed-processing-setup.rst
docs/source/gs-processing/usage/emr-serverless.rst
graphstorm-processing/docker/0.2.1/emr-serverless/Dockerfile.cpu
graphstorm-processing/docker/build_gsprocessing_image.sh
graphstorm-processing/docker/push_gsprocessing_image.sh
graphstorm-processing/pyproject.toml
graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json

* Bumps library version to 0.2.1.
* Add arm64 image support for EMR Serverless.
* ~~Add SageMaker Dockerfile with Spark 3.4 for 0.2.1.~~

[GSProcessing] Bump version to 0.2.1, add support for arm64 images for EMR Serverless

---

python/graphstorm/model/lm_embed.py

When we unfreeze the LM model, we don't need to clean up the cache if the number of train nodes is 0.

Fix a bug in unfreeze

---

docs/source/tutorials/quick-start.rst
python/graphstorm/gconstruct/remap_result.py
python/graphstorm/model/utils.py
tests/end2end-tests/check_infer.py
tests/end2end-tests/check_np_infer_emb.py
tests/end2end-tests/data_process/check_emb_remap.py
tests/end2end-tests/data_process/gen_emb_predict_remap_test.py
tests/end2end-tests/data_process/gen_node_predict_remap_test.py
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/test.sh
tests/unit-tests/test_utils.py

The file names of temporal output embedding files and node prediction files are confusing.
Update the file names.

[Bugfix] Update temporal emb and prediction file names

---

docs/source/tutorials/quick-start.rst
python/graphstorm/gconstruct/remap_result.py

[Document] Update doc about saved prediction results and embeddings

---

python/graphstorm/gconstruct/remap_result.py

remap_result.py can not handle the case when there are unknown arguments.
Resolve the issue.

Make remap_result more robust to unknown input args

---

python/graphstorm/gconstruct/remap_result.py
tests/end2end-tests/data_process/test.sh
tests/unit-tests/gconstruct/test_remap_result.py

When doing remap_result in a distributed way. It is possible that some processes are still collecting remap tasks (scanning the embedding files and prediction files) while others have finished the tasks and start removing processed files. This will cause an read/delete contention.

[Bug fix] Fix the read/delete contention bug when running distributed remaping result/emb

---

python/graphstorm/sagemaker/utils.py

`S3Downloader.download` use S3 path prefix match to find all matched file to download. This is different from folder match.
Add "/" to the S3 path when downloading partitions

[Bug fix] Fix ShageMaker S3 path bug

---

python/graphstorm/gconstruct/remap_result.py
tests/unit-tests/gconstruct/test_remap_result.py

When --column-names does not cover all builtin names, the remap will crash
Related issue: #674 

[Bug fix] Fix a bug when --column-names does not cover all builtin names

---

.github/workflow_scripts/e2e_check.sh
docs/source/configuration/configuration-run.rst
python/graphstorm/config/argument.py
python/graphstorm/dataloading/dataset.py
python/graphstorm/gconstruct/construct_graph.py
tests/end2end-tests/data_gen/movielens_homogeneous.json
tests/end2end-tests/data_gen/process_movielens.py
tests/end2end-tests/data_process/check_homogeneous.py
tests/end2end-tests/data_process/homogeneous_test.sh
tests/unit-tests/data_utils.py
tests/unit-tests/gconstruct/test_construct_graph.py
tests/unit-tests/test_config.py
tests/unit-tests/test_dataloading.py
training_scripts/gsgnn_ep/ml_ec_homogeneous.yaml
training_scripts/gsgnn_np/ml_nc_homogeneous.yaml

Homogeneous Graph Optimization: https://github.com/awslabs/graphstorm/pull/686
Homogeneous Graph Construction Optimization: https://github.com/awslabs/graphstorm/pull/683

[Homogeneous Graph Optimization] Homogeneous Graph Optimization 

---

python/graphstorm/gconstruct/utils.py
tests/unit-tests/gconstruct/test_gconstruct_utils.py

Numpy has a bug when storing a list of objects in numpy memmap array. We should avoid saving such a list to a memmap array.

Fix a bug in gconstruct when saving intermediate data on disks

---

docs/source/advanced/own-models.rst
docs/source/configuration/configuration-run.rst
examples/customized_models/HGT/hgt_nc.py
examples/peft_llm_gnn/main_nc.py
examples/peft_llm_gnn/nc_config_Video_Games.yaml
python/graphstorm/gsf.py
python/graphstorm/tracker/graphstorm_tracker.py
python/graphstorm/tracker/sagemaker_tracker.py

- This PR changes the input argument of `GSTaskTrackerAbc` from `GSConfig` object into an integer because the `GSTaskTrackerAbc` only needs an integer to set the `log_report_frequency` attribute. 
- Using the `GSConfig` object will prevent users from using task tracker to monitor running process because creating a GSConfig is NOT publicly open, and is very complex.
- Decouple the `GSTaskTracker` from using `GSConfig` could help users to construct task trackers and use them in the GraphStorm programming APIs.

[Enhancement] change the input argument of GSTaskTrackerAbc to be an integer

---

python/graphstorm/config/argument.py
python/graphstorm/dataloading/__init__.py
python/graphstorm/dataloading/dataloading.py
python/graphstorm/dataloading/sampler.py
python/graphstorm/gconstruct/transform.py
python/graphstorm/model/edge_decoder.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
tests/end2end-tests/create_data.sh
tests/end2end-tests/data_gen/movielens_lp_hard.json
tests/end2end-tests/data_gen/process_movielens.py
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/unit-tests/test_dataloading.py

Add edge hard negative support.

---

python/graphstorm/dataloading/dataloading.py
tests/unit-tests/test_dataloading.py

*What is the bug:*
When fixed_test_size is set while the number of testing edges are smaller than fixed_test_size, GraphStorm only print a warning of setting the fixed_test_size to the number of testing edges, but it does not take the real action. In certain cases, the link prediction test dataloader will generate empty mini-batches which will crash the testing process.
Fix the bug and update the unit tests.

BugFix: Fix the bug when fixed_test_size is set while the number of testing edges are smaller than fixed_test_size

---

python/graphstorm/run/launch.py

When launching remap commands in a distributed env, launch.py continuously appends new arguments into the launch command. For example:
```
PYTHONPATH=/opt/conda/bin:/root/dgl/tools:/opt/ml/code/graphstorm/python; /opt/conda/bin/python3 -m graphstorm.gconstruct.remap_result --cf config.yaml --restore-model-path /opt/ml/gsgnn_model --save-embed-path /tmp/infer_output/embs --save-embed-path /tmp/infer_output/embs --ip-config ip_list.txt --part-config metadata.json --rank 0 --world-size 16 --with-shared-fs False --num-processes 1 --output-chunk-size 100000 --preserve-input False --rank 1 --world-size 16 --with-shared-fs False --num-processes 1 --output-chunk-size 100000 --preserve-input False
PYTHONPATH=/opt/conda/bin:/root/dgl/tools:/opt/ml/code/graphstorm/python; …
```

[Bugfix] Fix a bug in launch.py when it is lauching remap commands.

---

graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_noop_transformation.py
graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
graphstorm-processing/tests/test_dist_noop_transformation.py

For now we also parse all numerical CSV values as float64. In the future we'll allow the use the option to choose, defaulting at float32.
*Issue #, if available:* Fixes #706
* For CSV numerical feature input always parse as float64. We plan to allow this to be user-defined in the future.
* For CSV regression label input always parse as float64. We plan to allow this to be user-defined in the future.
* For Parquet numerical feature input for noop transformation, use the input's data type, to avoid precision loss by converting to float32.
* For CSV numerical input for noop transformation (which is parsed as string), output to float64.
*How this was tested*:
* Added relevant unit test
* Tested on generated graph dataset with integer features with values up to 80M, …

[GSProcessing] Fix support for large integer values for noop transfomation

---

python/graphstorm/gconstruct/utils.py
tests/unit-tests/gconstruct/test_construct_graph.py

Add a mechanism to balance training/val/test sets in each graph partition. This is important for distributed training.
https://github.com/awslabs/graphstorm/issues/715

Balance the training set in graph partitioning

---

tools/README.md
tools/graph_sanity_check.py

In some cases, a user may provide a graph with invalid features. For example, some node features are NaN or Inf. 
The script introduced in this PR can be used by users to do sanity checks to see whether the node/edge features and node/edge masks are valid.

Add a tool to do graph data sanity check

---

python/graphstorm/config/argument.py
tests/unit-tests/test_config.py

By design and implementation, the contrastive loss function requires the node embedding be normalized.
Change the default lp_embed_normalizer to L2_norm when the loss function is contrastive loss.

Set default node embedding normalization method of contrastive loss to l2 norm.

---

docs/source/configuration/configuration-run.rst
python/graphstorm/config/argument.py
python/graphstorm/model/gnn.py
python/graphstorm/model/node_glem.py

This PR set default values for the sparse_optimizer_lr and weight_decay in Models' `init_optimizer()`. 
Reasons of this PR:
1. Most of users did not modify the two arguments values, rather than use values preset in our yaml files.
2. Set the two arguments will make API calls complex.

[Enhancement] Add default values for sparse_optimizer_lr and weight_decay

---

graphstorm-processing/docker/0.2.2/emr-serverless/Dockerfile.cpu
graphstorm-processing/docker/0.2.2/sagemaker/Dockerfile.cpu
graphstorm-processing/docker/README.md
graphstorm-processing/docker/build_gsprocessing_image.sh
graphstorm-processing/docker/push_gsprocessing_image.sh

* We switch away from using `pipenv` in the SageMaker image, relying instead on on the poetry-generated requirements.txt file to install dependencies. 
* Also switch to images having `prod` target by default (although this requires `poetry` to be installed on the image building environment).
* Update out-of-date README files.
Unit tests+Ran a SageMaker job with ml-25m data.

[GSProcessing] Make SageMaker image build faster and smaller.

---

python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/run/gsgnn_np/gsgnn_np.py
tests/end2end-tests/graphstorm-ec/mgpu_test.sh
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh

There is a bug in all the training scripts, when `save_embed_path` is set to a path and the backend is set to `nccl`. The restored model (used for computing the embedding with the best model) is not moved to GPU and will cause a `nccl` all_reduce error.
Fix the bug.

[Bug fix] Add NCCL test for save embedding during training and fix device bugs.

---

.github/workflow_scripts/e2e_mgpu_check.sh
python/graphstorm/model/embed.py
python/graphstorm/model/gnn.py
python/graphstorm/model/utils.py
python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_np/np_infer_gnn.py
python/graphstorm/wholegraph/wholegraph.py
tests/end2end-tests/check_np_infer_emb.py
tests/end2end-tests/graphstorm-ec/mgpu_test.sh
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh

This PR fixes some bugs in WholeGraphSupport: https://github.com/awslabs/graphstorm/pull/734 and add end2end test: https://github.com/awslabs/graphstorm/pull/732

[WholeGraph] Setup CI for WholeGraph support

---

python/graphstorm/config/argument.py
python/graphstorm/gsf.py
python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_np/gsgnn_np.py
python/graphstorm/run/gsgnn_np/np_infer_gnn.py
tests/end2end-tests/graphstorm-ec/mgpu_test.sh
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh

This is to address the concern brought up here: https://github.com/awslabs/graphstorm/pull/737#discussion_r1491769425. It changes the flag name `use-wholegraph-sparse-emb` --> `use-wholegraph-embed`, in consistent with  https://github.com/awslabs/graphstorm/pull/737.

[WholeGraph] Rename the flag for wholegraph sparse embedding 

---

graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
graphstorm-processing/tests/test_converter.py

* Allow gconstruct config input for feature column name be a single string.

[GSProcessing Bug Fix] Fix a bug for GConstruct Config Converter

---

python/graphstorm/config/config.py
python/graphstorm/gsf.py
python/graphstorm/model/__init__.py
python/graphstorm/model/gat_encoder.py
python/graphstorm/model/gatv2_encoder.py
tests/end2end-tests/data_process/homogeneous_test.sh
tests/unit-tests/test_gnn.py

Add GATv2 model as a built-in model.
Performance:
|     | ogbn-arxiv | ogbn-product |
|---|---|---|
| gat (batchsize=512) |  0.7061  |  0.7836 |
| gatv2 (batchsize=512) | 0.7134 | 0.8024 |

Add builtin GATv2 model

---

docs/source/gs-processing/gs-processing-getting-started.rst
docs/source/gs-processing/usage/amazon-sagemaker.rst
docs/source/gs-processing/usage/emr-serverless.rst
docs/source/gs-processing/usage/example.rst
docs/source/gs-processing/usage/row-count-alignment.rst
graphstorm-processing/docker/push_gsprocessing_image.sh
graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
graphstorm-processing/graphstorm_processing/repartition_files.py
graphstorm-processing/scripts/run_distributed_processing.py
graphstorm-processing/scripts/run_repartitioning.py
graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
graphstorm-processing/tests/test_repartition_files.py

With this change we allow the re-partition step to run on the leader instance, removing the need to run a separate job for it. If no files need re-partitioning, and only Parquet modification is needed for labels/masks we _always_ apply that on the leader.
To accomplish this we make the following changes:
* Add new `--do-repartition` argument
* Refactor repartition_files.py to allow separate execution of just Parquet metadata modification, and full repartition that runs both the row count alignment and the Parquet metadata modification.
* As part of this refactoring we also split the previously verbose `main` function into multiple smaller functions to allow easier maintenance. Each step is now performed by a separate function, namely …

[GSProcessing] Allow re-partitioning to run on the Spark leader

---

graphstorm-processing/docker/0.3.0/emr-serverless/Dockerfile.cpu
graphstorm-processing/docker/0.3.0/sagemaker/Dockerfile.cpu
graphstorm-processing/docker/push_gsprocessing_image.sh
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/pyproject.toml
graphstorm-processing/scripts/run_distributed_processing.py

* Optimizations for edge re-mapping:
* When an edge is homogeneous (same src and dst node type) we cache and re-use the node id mapping DF instead of loading from storage twice. 
* Remove enforced re-partitions where possible, because they'd trigger entire DF shuffles.
* These changes combined have improved total job runtime by up to 33% in a random graph with 10B edges and 1B nodes.
* Bumps GSProcessing version to 0.3.0.
* Allows Spark up to 3.5 in project dependencies.
* Adds 0.3.0 Dockerfiles with Spark 3.5 for emr-s and sagemaker.
*Testing*
pytest, test jobs on SageMaker and EMR-S using the latest image versions with ml-100k, and large-scale test on SM with 1B-edges-100M-nodes-1024feat graph.
By submitting this pull request, I confirm …

[GSProcessing] Move to Spark 3.5, bump version to 0.3.0, add homogeneous edge mapping optimization

---

docker/Dockerfile.local
docker/build_docker_oss4local.sh
docker/build_docker_sagemaker.sh
docs/source/install/env-setup.rst
docs/source/scale/distributed.rst
docs/source/scale/sagemaker.rst

Motivation: we want to be able to run local CPU clusters for cost-efficient partition and inference. Also the 11.7 Nvidia image will be EOL and removed by Nvidia in July 2024.
* Move local image to CUDA 12.1, ~~DGL 2.1.0~~
* Add the option to create CPU images for local clusters, allowing us to run partition/inference in CPU local clusters.
* Also changes tagging for SageMaker image to include image type as tag suffix, cpu/gpu.
Created local CPU and GPU clusters on EC2, run example ACM job.

[Docker] Move local image to CUDA 12.1. Add option for CPU local image.

---

examples/peft_llm_gnn/README.md

Update GPeft example Readme

---

python/graphstorm/gconstruct/construct_graph.py
python/graphstorm/gconstruct/remap_result.py
python/graphstorm/gconstruct/transform.py
python/graphstorm/gconstruct/utils.py
tests/end2end-tests/data_process/data_gen.py
tests/end2end-tests/data_process/test.sh
tests/end2end-tests/data_process/test_custom_mask_data.py
tests/unit-tests/gconstruct/test_construct_graph.py
tests/unit-tests/gconstruct/test_transform.py

#789 
This is the first PR to implement #789. We need to allow use to define train, validation and test mask names themselves.

[GConstruct] Allow users define train/validation/test masks

---

docs/source/api/graphstorm.eval.rst
examples/peft_llm_gnn/main_lp.py
python/graphstorm/config/argument.py
python/graphstorm/eval/__init__.py
python/graphstorm/eval/eval_func.py
python/graphstorm/eval/evaluator.py
python/graphstorm/inference/graphstorm_infer.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
python/graphstorm/trainer/ep_trainer.py
python/graphstorm/trainer/gsgnn_trainer.py
python/graphstorm/trainer/lp_trainer.py
python/graphstorm/trainer/np_trainer.py
tests/unit-tests/test_dist_eval.py
tests/unit-tests/test_evaluator.py

*Issue #757, if available:*
This is the 2nd PR of the Evaluator refactor work, which adds `GSgnnRegressionEvaluator`, `GSgnnLPEvaluator`, and `GSgnnPerEtypeLPEvaluator`. In addition, this PR also change the name of `GSgnnLPEvalInterface` to `GSgnnMrrLPEvalInterface`, making the meaning of the interface more clear.

[Refactor] Regression, LP, and PerEtypeLP evaluators

---

docs/source/api/graphstorm.eval.rst

This is the final PR for evaluator refactoring, which refines the doc string of evaluators.

[Doc] Final refine documents and tutorial for evaluator refactoring

---

docs/source/advanced/own-models.rst
docs/source/api/graphstorm.eval.rst
examples/customized_models/HGT/hgt_nc.py
examples/peft_llm_gnn/main_lp.py
examples/peft_llm_gnn/main_nc.py
examples/standalone_mode_demo.ipynb
examples/temporal_graph_learning/main_nc.py
python/graphstorm/config/argument.py
python/graphstorm/eval/__init__.py
python/graphstorm/eval/eval_func.py
python/graphstorm/eval/evaluator.py
python/graphstorm/inference/graphstorm_infer.py
python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
python/graphstorm/run/gsgnn_np/gsgnn_np.py
python/graphstorm/run/gsgnn_np/np_infer_gnn.py
python/graphstorm/trainer/ep_trainer.py
python/graphstorm/trainer/gsgnn_trainer.py
python/graphstorm/trainer/lp_trainer.py
python/graphstorm/trainer/np_trainer.py
tests/unit-tests/test_dist_eval.py
tests/unit-tests/test_evaluator.py
tests/unit-tests/test_inferrer.py
tests/unit-tests/test_trainer.py

*Issue #757, if available:*
This PR includes code refactor of GraphStorm "**Evaluators**". And all codes, examples and documentations are refactored accordingly.
The major changes include:
1. Unified `GSgnnInstanceEvaluator` and `GSgnnLPEvaluator` classes with `GSgnnBaseEvaluator` plus interface classes, i.e., `GSgnnPredictionEvalInterface` and `GSgnnLPRankingEvalInterface`. In such way, all sub evaluators share the same properties, and also can have different evaluation methods according to the interfaces they implemented.
2. Replaced `GSgnnAccEvaluator` with `GSgnnClassificationEvaluator`, which is implemented by extending `GSgnnBaseEvaluator` and `GSgnnPredictionEvalInterface`. Its behavior is nearly the same as the `GSgnnAccEvaluator`.
3. Modified …

[Refactor] Refactor Evaluator

---

.github/workflow_scripts/lint_check.sh

Remove the part for installing the graphstorm when running lint test.

[Enhancement] Remove GSF dependency on lint check CI

---

python/graphstorm/__init__.py
python/graphstorm/gsf.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py

Related to #789 
1. decouple the code of creating decoders from the code of creating built-in models to make the code of creating decoders more reusable. 
2. add `get_builtin_lp_train_dataloader_class` and `get_builtin_lp_eval_dataloader_class` in gsf.py

Refactor gsf.py to make the code of creating decoders and creating link prediction dataloders reusable.

---

docker/build_docker_oss4local.sh

* To pull the CPU source image we need to authenticate with Amazon Public ECR gallery using the AWS cli. This is not needed to build the GPU image, so we move that auth step under the CPU branch, to avoid customers having to add the permission to their roles if they're only building the GPU image.

[Docker] Move the Amazon ECR Public Gallery auth to only the CPU branch of the local build script.

---

python/graphstorm/model/node_gnn.py
tests/unit-tests/test_gnn.py

Originally, node_mini_batch_predict expect its argument `loader` is a node dataloader with 0 GNN layers (fanout=[]). However, this can not been guaranteed.
Change the implementation to make it work with node dataloader with/without GNN layers.

[BugFix] Fix node class full graph infer

---

python/graphstorm/model/__init__.py
python/graphstorm/model/edge_gnn.py
python/graphstorm/model/lp_gnn.py
python/graphstorm/model/node_gnn.py
tests/unit-tests/test_gnn.py

#789 
As multi-task learning trainer will invoke edge_mini_batch_predict, lp_mini_batch_predict and node_mini_batch_predict when conducting evaluation or testing, refactor the code to allow the functions to work with different decoders.

[Multi-task Learning] Refactor graphstorm.model for multi-task learning.

---

docs/source/configuration/configuration-gconstruction.rst
python/graphstorm/gconstruct/construct_graph.py

*Issue #796 , if available:*
This PR changed the behavior of saving the new gconstruct configuration file. If users do not specify the `--output-conf-file` argument, we will automatically save it to the `output-dir` folder with the name "data_transform_new.json".
This PR also update the Configuration documents, adding explanations of the `--output-conf-file` argument.

[Enhancement] Change save new gconstruct configuration file behavior

---

docs/source/index.rst

This PR add the link in the document index page to let the new API example Notebook 2 appear in the menu bar. 

[Doc] Fix notebook 2 is not listed in index page issue

---

python/graphstorm/dataloading/dataloading.py
python/graphstorm/model/__init__.py
python/graphstorm/model/multitask_gnn.py
tests/unit-tests/test_gnn.py

#789 
GSgnnMultiTaskSharedEncoderModel allows multiple tasks to share the same GNN encoder but have separate decoders for each task.

[Multi-task Learning] Add GSgnnMultiTaskSharedEncoderModel

---

graphstorm-processing/docker/push_gsprocessing_image.sh
graphstorm-processing/graphstorm_processing/constants.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/graphstorm_processing/repartition_files.py
graphstorm-processing/tests/test_repartition_files.py

* We change the way we configure the Spark env, to only create our own config for SageMaker, as EMR/EMRS will have pre-configured defaults.
* We introduce some enum classes to better communicate execution environment and filesystem type
* We try to cache DFs that are used multiple times to avoid re-computation
* Do not use `:` in the data paths, as it can cause errors when moving the data to local filesystems.

[GSProcessing] Improve Spark config to better support EMR/EMRS, small optimizations

---

python/graphstorm/gconstruct/construct_graph.py
python/graphstorm/gconstruct/transform.py

The original train/val/test mask fields check is too strict. As there can be some exception when users want to provide masks through node features or some tasks are sharing the same mask.
Relax the check and turn the assertion into warning.

Relax the train/val/test mask check for multi-task learning

---

.github/workflow_scripts/e2e_mgpu_check.sh
python/graphstorm/dataloading/dataloading.py
python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
tests/end2end-tests/data_gen/movielens_multi_task.json
tests/unit-tests/test_dataloading.py
training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml

The way to set the eval_fanout when creating the validation datalaoder for a link prediction task in multi-task learning setting is incorrect. It will crash the training script.
Update the code to use the global eval_fanout for the validation dataloader.

[Bugfix] Fix eval_fanout of validation dataloader for lp task in multi-task learning

---

python/graphstorm/gpartition/dist_partition_graph.py

All other launchers use `--ip-config` to refer to the IP list file, this PR makes the dist part launcher be consistent with th rest.

Make IP config argument for distpart consistent with the rest of GSF

---

python/graphstorm/trainer/ep_trainer.py
python/graphstorm/trainer/lp_trainer.py
python/graphstorm/trainer/np_trainer.py

This PR fixed the error when calling `fit()` function in `ep_trainer` and `lp_trainer` without specifying the `save_model_frequency` value, which will cause an operation error when compare None to int in the code `save_model_frequency > 0`.
Also add default value and its explanation in the doc string for all three kinds of trainer.

[Fix] Fix save_model_frequency None error in trainer

---

python/graphstorm/model/__init__.py
python/graphstorm/model/multitask_gnn.py
python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
python/graphstorm/trainer/mt_trainer.py
tests/unit-tests/test_gnn.py
tests/unit-tests/test_trainer.py
tests/unit-tests/util.py
training_scripts/gsgnn_mt/ml_nc_ec_er_lp.yaml

#789 
Previously, in the eval() function of GSgnnMultiTaskLearningTrainer, both link prediction and node feature reconstruction tasks use the node embeddings computed with the entire graph. This will cause test edge leakage for link prediction tasks and target node node feature leakage for node feature reconstruction tasks. This PR fixes this issue.

Update multi-task evaluation logic to avoid information leakage issue in lp and nfeat reconstruct task evaluation.

---

docs/source/gs-processing/gs-processing-getting-started.rst
docs/source/gs-processing/usage/example.rst
graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/base_dist_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/pyproject.toml
graphstorm-processing/tests/resources/precomputed_transformations/user_state_categorical_transformation.json
graphstorm-processing/tests/test_dist_category_transformation.py
graphstorm-processing/tests/test_dist_executor.py
graphstorm-processing/tests/test_dist_heterogenous_loader.py

* Follow-up to #857 
* Allow us to re-apply a previously saved categorical transformation to new data. See below for design details.
To be able to re-apply the categorical transformations that we create using the code in #857 , we first create a mapping from original string to one-hot representation, that we read from the saved JSON file, then use a UDF to use the mapping(s) on the column(s).
The `DistributedTransformation` class from which all transformation implementations inherit, gains a new function, `apply_precomputed_transformation`. When a pre-computed transformation JSON file exists in the input, and the feature is one of those listed in that file, we use this function to re-apply the existing transformation instead of creating a …

[GSProcessing] Add pre-computed categorical transformation loading

---

python/graphstorm/gpartition/metis_partition.py

* Previously we were calling the `pm_dglpart` executable through `mpirun` using only a single/process worker. This PR pulls in a necessary file that `parmetis_preprocess.py` creates in the wrong path, and fixes the number of workers used to match the number of partitions.
The parmetis program implicitly expects a file named `<graph-name>_stats.txt` to be in the current working directory, the way the call is implemented at least. Actually the reference DGL implementation is wrong, it passes the graph_name whereas pm_dglpart actually expects a prefix path to which it appends _stats.txt. It just so happens that if we prefix the graph_name to a file in the cwd, and name it graph-name_stats.txt pm_dglpart will pick it up and use it.
A more …

Fix ParMETIS call so it uses all workers in cluster.

---

README.md

Update Readme to add a link to graphstorm paper

---

python/graphstorm/model/hgt_encoder.py
python/graphstorm/model/rgat_encoder.py
python/graphstorm/model/rgcn_encoder.py

To avoid excessive warning logs from RGCN, RGAT, and HGT encoders, this PR ensures that identical warnings (warnings that share the same message) are printed only once.

Reduce the number of warning prints of heterogeneous GNN encoders when some nodes do not have in edges

---

docs/source/advanced/multi-task-learning.rst
docs/source/tutorials/own-data.rst

#789 
Add doc for multi-task learning.

[Documentation] Add doc for multi-task learning

---

python/graphstorm/dataloading/dataset.py

#773
If the size of the training set is smaller than the number of trainers (GPUs), it is possible that some trainers will not have any training data. The training loop will finally fail in this case.
Update the error message to provide more information for users to debug the input data.

Add more information in the error message when the training set is empty or too small.

---

python/graphstorm/gpartition/__init__.py
python/graphstorm/gpartition/dist_partition_graph.py
python/graphstorm/gpartition/random_partition.py
python/graphstorm/sagemaker/sagemaker_partition.py
tests/unit-tests/gpartition/conftest.py
tests/unit-tests/gpartition/test_random_partition.py

We use this commit as a base for range partitioning.
Fixes #802 
* Download files in parallel from S3 for SageMaker partition.
* Copy raw_id_mappings from the input path to the generated DGL graph path for SageMaker and local. 
* Change dtype of random partition assignment pyarrow array, from int64 to uint8 for cases where num_parts < 256, uint16 otherwise.
* Support getting SageMaker job information for both SageMaker Processing jobs, and SageMaker Training jobs, allowing us to use more instance types.
* Make gpartition unit test verification re-usable across partition algorithm implementations.
We use this PR as a base for RangePartition.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

[GPartition/SageMaker] Improvements to gpartition and SageMaker partition.

---

docs/source/gs-processing/usage/emr.rst
graphstorm-processing/docker/0.3.1/emr-serverless/Dockerfile.cpu
graphstorm-processing/docker/0.3.1/emr/Dockerfile.cpu
graphstorm-processing/docker/0.3.1/sagemaker/Dockerfile.cpu
graphstorm-processing/graphstorm_processing/constants.py
graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/pyproject.toml
graphstorm-processing/scripts/submit_gsp_emr_step.py

* Bump the version to 0.3.1, and add corresponding Dockerfiles
* Create a new launch script for EMR on EC2 that allows us to run a GSProcessing job as an EMR step, simplifying the UX.

[GSProcessing] Increment version. Add a simplified launch script for EMR on EC2.

---

python/graphstorm/model/multitask_gnn.py
tests/unit-tests/test_gnn.py

The loss funcs of GSgnnMultiTaskSharedEncoderModel are not added as nn.modules of GSgnnMultiTaskSharedEncoderModel. This will cause device error in some cases.
Adding loss funcs as a nn.ModuleDict() of GSgnnMultiTaskSharedEncoderModel.

[Bugfix] Loss funcs for multitask learning should also be added as torch nn.module

---

python/graphstorm/model/node_decoder.py
tests/unit-tests/test_decoder.py

Code to reproduce the error:
```
>>> from graphstorm.model import EntityRegression
>>> decoder = EntityRegression(h_dim=in_dim, out_dim=10)
>>> print(decoder.out_dims)
1
```
The decoder.out_dims should be 10.
Fix the bug

[Bugfix] Fix EntityRegression.out_dims() dimension mismatch

---

graphstorm-processing/graphstorm_processing/config/label_config_base.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_bucket_numerical_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/graphstorm_processing/repartition_files.py
graphstorm-processing/mypy.ini

* During the refactor with https://github.com/awslabs/graphstorm/pull/870 we moved the loader to be a class var for DistributedExecutor, but because the S3 path is not unit tested we missed on case where the output is on S3 and the user requests repartition on leader.
* This error was actually picked up by mypy, I fixed some other potential issues and type annotations here.
Pre-commit, unit tests, and one test SageMaker job all succeed.
The S3 codepath can only be integration tested currently.

[GSProcessing] Fix bug in repartition on leader, fix mypy errors and latent bugs

---

python/graphstorm/run/launch.py

Fixes https://github.com/awslabs/graphstorm/issues/848
* Ensure the extra env vars are added to the remap launch command
Ran the [standalone mode](https://graphstorm.readthedocs.io/en/v0.3/tutorials/quick-start.html) example with extra parameter `--extra-envs LD_LIBRARY_PATH="/opt/gs-venv/lib/python3.9/site-packages/dgl/:$LD_LIBRARY_PATH"`, ensured that the command submitted by the launcher included the extra env vars as:
```bash
cd /tmp/ogbn-arxiv-nc; (export LD_LIBRARY_PATH=/opt/gs-venv/lib/python3.9/site-packages/dgl/:; (export PYTHONPATH=/graphstorm/python/:/root/dgl/tools/::/root/dgl/python ; /opt/gs-venv/bin/python -m graphstorm.gconstruct.remap_result --cf /graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml --save-model-path …
```

Ensure extra env vars are propagated to remap command

---

graphstorm-processing/docker/0.3.1/emr-serverless/Dockerfile.cpu
graphstorm-processing/graphstorm_processing/distributed_executor.py

* We update the source image for EMRS to use the 7.1.0 image
* We add a file in the image to ensure we correctly identify the execution environment.

[GSProcessing] Update EMRS image to 7.1.0, add file in image to ensure we recognize execution env.

---

python/graphstorm/gconstruct/utils.py

During gconstructing, when a child process crashes (for example due to OOM), the main process will hang for ever.
Raise an runtime error when child process crashes.

[Bug] Report child process running errors in gconstruct

---

graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
graphstorm-processing/tests/test_dist_numerical_transformation.py

Also adds tests and fixes some pylint errors in test file.
* Previously if a user provided a numerical transformation config where imputer, norm, or separator (for multi-num) was missing, the job would fail since the object could not be instantiated without all required arguments, although we list those args as optional.
* This PR adds default values for all optional args in the classes' __init__
* Also adds a couple of tests and fixes a few pylint errors in the test file.
* Also add a test for the case where the multi-numerical input is a vector value (which is the case for Parquet vector inputs)

[GSProcessing] Add default argument values for optional numerical transformation kwargs

---

graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py

* Fixes corner case where a feature value might not be one of int/float (we don't cast Parquet input types), replacing with the more general `numbers.Number`.
Example of how to trigger a failure, as observed by a customer:
```python
>>> import numbers
>>> import decimal
>>> dn = decimal.Decimal(5)
>>> intnum = 5
>>> isinstance(intnum, (float, int))
True
>>> isinstance(dn, (float, int))
False
>>> isinstance(dn, numbers.Number)
True
```

[GSProcessing] Fix isinstance check for numerical features

---

python/graphstorm/dataloading/dataset.py
python/graphstorm/model/multitask_gnn.py
tests/end2end-tests/create_data.sh
tests/end2end-tests/data_gen/movielens_small_val.json
tests/end2end-tests/graphstorm-ec/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh
tests/unit-tests/data_utils.py
tests/unit-tests/test_dataloading.py

Fix the bug when the number of val/test samples is small

---

docs/source/cli/model-training-inference/configuration-run.rst
python/graphstorm/config/argument.py
tests/unit-tests/test_config.py

Support `node_feat_name` input to add space like: `node_type_a:feat_name_1, feat_name_2`

[Bug Fix] Trim leading/tailing space for `node_feat_name`

---

python/graphstorm/model/edge_decoder.py
tests/unit-tests/test_decoder.py

There is a bug when calling `calc_distmult_pos_score` to compute scores of positive edges during testing. Though the bug will not cause any performance issue as mathematically, reordering tensor position in DistMult will not cause any problem.

[BugFix] Fix distmult evaluation score calculation

---

README.md
docs/source/install/env-setup.rst
setup.py

* Python 3.7 went EOL on 2023-06-27, we remove support for it for GraphStorm 0.4.
For a full list of language/library features that can now be used see https://docs.python.org/3/whatsnew/3.8.html

Move minimum Python version to 3.8 for GraphStorm

---

docs/source/cli/model-training-inference/configuration-run.rst
python/graphstorm/config/argument.py
python/graphstorm/gsf.py
python/graphstorm/run/gsgnn_dt/distill_gnn.py
python/graphstorm/run/gsgnn_emb/gsgnn_node_emb.py
python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
python/graphstorm/run/gsgnn_mt/gsgnn_mt.py
python/graphstorm/run/gsgnn_mt/mt_infer_gnn.py
python/graphstorm/run/gsgnn_np/gsgnn_np.py
python/graphstorm/run/gsgnn_np/np_infer_gnn.py

* We introduce support for GraphBolt training and inference, see https://docs.dgl.ai/stochastic_training/index.html for details
* We add a new optional argument `--use-graphbolt` to the configuration. When set to true that sets the dgl.initialize call to include `use_graphbolt=True`, on supported DGL versions.
* For versions of DGL < 2, we print a warning and run regular distributed environment init.

Support for launching jobs with GraphBolt enabled (GraphBolt support PR1)

---

docs/source/advanced/link-prediction.rst
docs/source/cli/model-training-inference/configuration-run.rst
examples/paper_experiments/README.md
examples/paper_experiments/training_configs/link_prediction/lp_also_buy_1_layer_rgcn_dot_adversarial_entropy_loss_joint_32_negative.yaml
python/graphstorm/config/argument.py
python/graphstorm/gsf.py
python/graphstorm/model/loss_func.py
tests/end2end-tests/graphstorm-lp/test.sh
tests/unit-tests/test_config.py
tests/unit-tests/test_loss.py

#954 
Add adversarial negative loss to cross-entropy loss for link prediction tasks.
Adversarial negative loss can boast the model performance. The following experiments follow the same setting as in https://github.com/classicsong/graphstorm/blob/focal-loss/examples/paper_experiments/training_configs/link_prediction/lp_also_buy_1_layer_rgcn_dot_entropy_loss_joint_32_negative.yaml.
With adversrial negative loss, the best test MRR increases from 0.380 to 0.8796 using the same setting as in [GraphStorm Paper](https://dl.acm.org/doi/pdf/10.1145/3637528.3671603).

Add adversarial negative option to cross-entropy loss for link prediction tasks

---

python/graphstorm/dataloading/dataloading.py
python/graphstorm/run/gsgnn_mt/gsgnn_mt.py

The training dataloader for link prediction use the default "train_mask" as the edge mask for gnn embedding computation. However, this assumption does not hold in multi-task learning.

[Bugfix] Excluding valid/test edges during link prediction training in multi-task learning setting

---

.github/workflow_scripts/e2e_check.sh
.github/workflow_scripts/e2e_gb_check.sh
docs/source/cli/graph-construction/distributed/gspartition/ec2-clusters.rst
docs/source/cli/graph-construction/single-machine-gconstruct.rst
python/graphstorm/gconstruct/construct_graph.py
python/graphstorm/gconstruct/utils.py
python/graphstorm/gpartition/dist_partition_graph.py
python/graphstorm/gsf.py
python/graphstorm/run/launch.py
setup.py
tests/end2end-tests/create_data.sh
tests/end2end-tests/data_gen/process_movielens.py
tests/end2end-tests/data_process/gpartition_test.sh
tests/end2end-tests/data_process/movielens_test.sh
tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh

* Add `--use-graphbolt` argument to GConstruct and GSPartition entry points. When set to `true`, we convert the graph data to GraphBolt format after partitioning.
* Add new `gpartition_test.sh` set of integration tests for GSPartition entry point. 
* Add new tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh set of integration tests for graph construction with GraphBolt enabled. Requires DGL >= 2.x.
* To accommodate this, we we modify `tests/end2end-tests/data_gen/process_movielens.py` so that it also produces a JSON file that can be used as input the the DistPart DGL pipeline.
* To parse and handle different DGL versions we use `importlib.metadata` and the `packaging` modules. We introduce an explicit dependency …

[GraphBolt] Add GraphBolt graph construction for GConstruct and GPartition (GraphBolt PR2)

---

python/graphstorm/gconstruct/utils.py
python/graphstorm/gpartition/convert_to_graphbolt.py
python/graphstorm/gpartition/dist_partition_graph.py
tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh

* Standalone entry point for conversion of DistDGL data to GraphBolt format. This can be used to convert existing data to GB, DGL does not provide an entry point for that.
* We'll also use this in our example/tutorial.

Add entry point for standalone GraphBolt conversion.

---

docs/source/advanced/multi-task-learning.rst
docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
graphstorm-processing/graphstorm_processing/config/label_config_base.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/graphstorm_processing/repartition_files.py
graphstorm-processing/tests/resources/repartitioning/partitioned_metadata.json
graphstorm-processing/tests/test_converter.py
graphstorm-processing/tests/test_dist_heterogenous_loader.py
graphstorm-processing/tests/test_dist_label_loader.py
graphstorm-processing/tests/test_repartition_files.py

Currently support only random mask generation.
Fixes #992
We add support for multi-task mask generation to GSProcessing.
~~To achieve this we add a boolean `is_multitask` class variable to `DistHeterogeneousGraphLoader`. We set this to true when there's more than one label defined in the input configuration.~~
~~When `is_multitask` is True, we append the label column name to the mask name of every label. For link prediction tasks, we append `_lp` to the mask name. We also modify `repartition_files.py` accordingly.~~
We use the same UX as with GConstruct: users are expected to provide a `mask_field_names` entry for each label they want to use in MT training.
We add an example to documentation and link to it from the main multi-task …

[GSProcessing] Initial support for multi-task mask generation

---

python/graphstorm/config/argument.py
tests/unit-tests/test_config.py

Fix the bug by disabling edge weight for lp loss when the loss function is contrastive loss.

[Bugfix] Link prediction contrastive loss does not work with edge weight for lp loss

---

.github/workflow_scripts/e2e_gb_check.sh
tests/end2end-tests/graphbolt-gs-integration/graphbolt-graph-construction.sh
tests/end2end-tests/graphbolt-gs-integration/graphbolt-training-inference.sh

* Add a test script that executes LP and NC training and inference tasks with GraphBolt enabled. To run on one instance we create-single partition versions of the ml-100k data, and use the same gconstruct/yaml configs as we do in our end2end CPU tests.
* Merging will close https://github.com/awslabs/graphstorm/issues/982

[GraphBolt] Add integration tests for LP and NC training and inference.

---

graphstorm-processing/docker/push_gsprocessing_image.sh

[GSProcessing Docker] Update push script for GSProcessing Docker Image

---

graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/tests/test_dist_executor.py

* GSProcessing makes providing a graph name optional. After https://github.com/awslabs/graphstorm/pull/1044 we were checking the graph name before we filled in default values. 
* We now provide a default value before the name validity check.
* Added some tests to check various graph naming cases.

[GSProcessing] Fix to make graph_name optional again

---

python/graphstorm/config/argument.py
tests/unit-tests/test_config.py

#1051
Fix the bug for wd_l2norm and alpha_l2norm

[Bugfix] Fix the case when the input value of wd_l2norm is using scientific notation.

---

python/graphstorm/gconstruct/file_io.py

The error report in file_io.py:get_in_files does not provide useful information when the input file dir does not exist.
Update the error report implementation.

[Enhancement] Improve the error report in gconstruct when files do not exist.

---

graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py

* When copying data from S3 to HDFS or EFS we can't use paths that contain colons `:`. We have already fixed this for edge structures and labels, this fixes it for features as well.

[GSProcessing] Replace colons in edge feature paths with underscores to ensure EFS compatibility.

---

.github/workflow_scripts/pytest_check.sh
inference_scripts/mt_infer/ml_nc_ec_er_lp_only_infer.yaml
inference_scripts/mt_infer/ml_nc_ec_er_lp_with_mask_infer.yaml
python/graphstorm/eval/eval_func.py
python/graphstorm/eval/evaluator.py
python/graphstorm/gsf.py
python/graphstorm/inference/graphstorm_infer.py
python/graphstorm/inference/lp_infer.py
python/graphstorm/inference/mt_infer.py
python/graphstorm/model/edge_decoder.py
python/graphstorm/model/lp_gnn.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/trainer/gsgnn_trainer.py
python/graphstorm/trainer/lp_trainer.py
python/graphstorm/trainer/mt_trainer.py
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-mt/mgpu_test.sh
tests/unit-tests/test_eval_func.py
tests/unit-tests/test_inferrer.py
tests/unit-tests/test_trainer.py

* Add Adjust Mean Rank Index LP metric. This metric is normalized by the candidate list size, allowing for easier comparison between datasets/models and negative edge sample counts.
* To get the list sizes we modify `run_lp_mini_batch_predict` and `lp_mini_batch_predict` to _conditionally_ return a tuple of `rankings, lengths` that allows us to calculate AMRI in the cases where it's needed. The return type is determined by a new argument added, with a default value, so the changes are backwards compatible, existing calls to the two functions will function as before.
* Add `LinkPredictionTestScoreInterface` as a common ancestor to `LinkPredictNoParamDecoder` and `LinkPredictLearnableDecoder`, this way we can ensure at runtime that the …

Add Adjusted Mean Ranking Index metric for Link Prediction

---

tests/unit-tests/gconstruct/test_transform.py

Got this error in a un-related PR. We fixed the previous check in another PR, now doing the second one:
```
[2024-11-07T18:45:49.137Z] ________________ test_fp_min_max_transform[float16-complex128] _________________
[2024-11-07T18:45:49.137Z] input_dtype = <class 'numpy.complex128'>, out_dtype = <class 'numpy.float16'>
[2024-11-07T18:45:49.137Z]     @pytest.mark.parametrize("input_dtype", [np.cfloat, np.float32])
[2024-11-07T18:45:49.137Z]     @pytest.mark.parametrize("out_dtype", [None, np.float16])
[2024-11-07T18:45:49.137Z]     def test_fp_min_max_transform(input_dtype, out_dtype):
[2024-11-07T18:45:49.137Z]         transform = NumericalMinMaxTransform("test", "test", out_dtype=out_dtype)
[2024-11-07T18:45:49.137Z]         max_val = …
```

Reduce sensitive for test_fp_min_max_transform to avoid flaky test

---

.github/workflow_scripts/pytest_check.sh
.gitignore
docker/push_gsf_container.sh
docker/sagemaker/Dockerfile.sm
docker/sagemaker/build_artifacts/start_with_right_hostname.sh
docs/source/advanced/using-graphbolt.rst
python/graphstorm/gpartition/convert_to_graphbolt.py
python/graphstorm/sagemaker/sagemaker_partition.py
python/graphstorm/sagemaker/utils.py
sagemaker/launch/common_parser.py
sagemaker/launch/launch_gconstruct.py
sagemaker/launch/launch_graphbolt_convert.py
sagemaker/launch/launch_infer.py
sagemaker/launch/launch_partition.py
sagemaker/launch/launch_train.py
sagemaker/run/gb_convert_entry.py
sagemaker/run/gconstruct_entry.py
sagemaker/run/train_entry.py
tests/sagemaker-tests/test_sagemaker_args.py

* Add a new SageMaker job to convert DistPart data to GraphBolt. This is our only option currently as there's no way to directly use S3 as a writable, shared file system in SageMaker, see https://github.com/awslabs/graphstorm/issues/1081 for details.
* The `sagemaker/launch_graphbolt_convert.py` will launch the SageMaker job, that downloads the entire partitioned graph to one instance, then runs the GB conversion, one partition at a time. Because DGL writes the new fused CSC graph representation in the same directory as the input data, we can't use one of SageMaker's FastFile modes to stream the data, as that creates read-only filesystems.
* [Optional] We also include an example of how one could use a SageMaker Pipeline to run the …

[SageMaker] [GraphBolt] Add support for launching GraphBolt jobs on SageMaker

---

python/graphstorm/gconstruct/file_io.py
tests/unit-tests/gconstruct/test_gconstruct_utils.py

* Reported by customer
* Previously if a user passed in a list of input files with a single wildcard path the path was treated as a regular (non-wildcard) path, leading to file not found error.
* We make the file parsing consistent by using the `expand_wildcard` and always passing a list of str to it.
* Add a test case where we used to fail

Fix GConstruct file parsing when input is a list with a single wildcard path

---

docs/source/cli/graph-construction/distributed/example.rst
graphstorm-processing/graphstorm_processing/data_transformations/dist_feature_transformer.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_bucket_numerical_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_numerical_transformation.py
graphstorm-processing/tests/test_dist_executor.py
graphstorm-processing/tests/test_dist_feature_transformer.py
graphstorm-processing/tests/test_dist_numerical_transformation.py

Fixes #985 
* We introduce saving and re-applying numerical transformations for all transforms except rank-gauss, which by definition cannot be reapplied.
* For the more complex transformations we re-construct the original PySpark transformer objects, by retaining the values needed for each transformation (e.g. the min and max values), creating tiny DFs that only contain those numbers and re-training the transformer on that tiny dataset. Then we can apply the trained transformer to the desired data and we get the same result.
* To reduce code duplication we pull out the core computations for standard and min-max normalization into their own functions (`_apply_standard_transform`, `_apply_minmax_transform`), which we can call from both the …

[GSProcessing] Add saving and re-applying for numerical transforms.

---

graphstorm-processing/graphstorm_processing/config/data_config_base.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/tests/resources/small_heterogeneous_graph/gsprocessing-config.json

* Some GConstruct or GSProcessing config files from customers could have file paths that start with `./` which works when input is local but break for S3. We fix this by removing the `./` prefix if it exists when parsing the input files.
* Add change to config we use for testing to verify the change works (although we'd probably need a more S3-specific test)

[GSProcessing] Fix parsing of file paths that start with "./"

---

python/graphstorm/model/utils.py
tests/unit-tests/test_model_save_load.py

In _get_sparse_emb_range, It is possible that start is also larger than num_embs. For example, when `num_embs = 11`, `world_size = 8`, and `rank is 7`, `start = 7 * 2`, which is `14 > 11`.

[Bugfix] Fix the bug when _get_sparse_emb_range return a start larger than num-of-embs

---

examples/acm_data.py
python/graphstorm/run/gsgnn_ep/ep_infer_gnn.py
python/graphstorm/run/gsgnn_ep/ep_infer_lm.py
python/graphstorm/run/gsgnn_ep/gsgnn_ep.py
python/graphstorm/run/gsgnn_ep/gsgnn_lm_ep.py
python/graphstorm/run/gsgnn_lp/gsgnn_lm_lp.py
python/graphstorm/run/gsgnn_lp/gsgnn_lp.py
python/graphstorm/run/gsgnn_lp/lp_infer_gnn.py
python/graphstorm/run/gsgnn_lp/lp_infer_lm.py
python/graphstorm/run/gsgnn_np/gsgnn_np.py
python/graphstorm/run/gsgnn_np/np_infer_gnn.py
tests/end2end-tests/create_data.sh
tests/end2end-tests/data_gen/movielens_ef_er.json
tests/end2end-tests/data_gen/movielens_ef_lp.json
tests/end2end-tests/data_gen/movielens_ef_nc_ec.json
tests/end2end-tests/graphstorm-ec/mgpu_test.sh
tests/end2end-tests/graphstorm-er/test.sh
tests/end2end-tests/graphstorm-lp/mgpu_test.sh
tests/end2end-tests/graphstorm-nc/mgpu_test.sh

This PR is the last one to configure run main function in NP, EP, and LP. The major contents include:
1. Add `edge_feat_name` argument to Node, Edge, and LinkPrediction Dataloaders in NP, EP, and LP main() funcitons.
2. Add end-to-end test cases for NC, EC, ER, and LP.
3. Modify the `acm_data.py` example data generation code to demo using edge features.

[Feature] Run config for using edge features

---

docker/local/Dockerfile.local
docker/parmetis/Dockerfile.parmetis
docker/sagemaker/Dockerfile.sm

* With the release of torchdata 0.10.0, installs of DGL==2.3.0 are broken.
* We pin the version of torchdata in our images to avoid errors.

Fix for error introduced by DGL's dependencies for Docker images

---

docker/build_graphstorm_image.sh
docker/parmetis/Dockerfile.parmetis
docker/push_graphstorm_image.sh
docker/sagemaker/Dockerfile.sm
docs/source/cli/model-training-inference/distributed/sagemaker.rst
docs/source/install/env-setup.rst

* Introduce new Docker build files to allow unified and single command build and push for GSF local and Sagemaker. 
* The change is backwards compatible, we deprecate the old build scripts in 0.4 and 0.5 and remove them in 0.6.  

Add build scripts for single-command build and push for local and sagemaker GS images

---

python/graphstorm/sagemaker/sagemaker_gb_convert.py

* The original GraphBolt on SageMaker PR was missing the internal (GSF library) implementation, we only provided the launch script and entry point. This adds the missing module in the GraphStorm library.

[SageMaker] Add SageMaker GraphBolt internal implementation

---

python/graphstorm/model/gnn_encoder_base.py

Previously (before adding edge feature in message passing), we do not require any block information, so the code works fine. Now as we require them for edge feats, we need to make a small fix about it. The error is only triggered in large dataset with workers > 24. Already test successfully with amazon-review dataset with this PR.

[Bug Fix] Fix Edge Feature None block error

---

docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
graphstorm-processing/graphstorm_processing/config/config_parser.py
graphstorm-processing/graphstorm_processing/config/label_config_base.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/pyproject.toml
graphstorm-processing/tests/test_converter.py
graphstorm-processing/tests/test_dist_heterogenous_loader.py
graphstorm-processing/tests/test_gsprocessing_config.py
python/graphstorm/gconstruct/file_io.py

NOTE: GSProcessing now requires list[str] for its custom split file config input.
* Update GSProcessingdocumentation for custom split files to match implementation.
* Make GSProcessing config parsing be equivalent to GConstruct by allowing only one of train/val/test to be defined. Previously GSProcessing required all, but GConstruct did not.
* Make the custom file input for GSProcessing to _require_ list of files. When possible we want GSProcessing input config to have _one_ way to define things, allowing easier verification and reducing use confusion.
* Also used GenAI to generate some tests for `gsprocessing.config` classes and functions that were previously untested.
By submitting this pull request, I confirm that you can use, modify, …

[GSProcessing] Update GSProcessing custom split config parsing and documentation to match GConstruct.

---

sagemaker/launch/common_parser.py

There is a typo in SUPPORTED_INFER_TASKS.
Change `comput_emb` to `compute_emb`

Fix typo in sagemaker launcher

---

python/graphstorm/gconstruct/file_io.py
tests/unit-tests/gconstruct/test_gconstruct_utils.py

* Allow directories as input to GConstruct, bringing it level with GSProcessing. 

[GConstruct] Allow directory paths as input to GConstruct

---

python/graphstorm/config/argument.py
python/graphstorm/gsf.py
python/graphstorm/model/__init__.py
python/graphstorm/model/edge_decoder.py
python/graphstorm/model/node_decoder.py
tests/end2end-tests/graphstorm-nc/test.sh
tests/unit-tests/data_utils.py
tests/unit-tests/test_decoder.py
tests/unit-tests/test_gsf.py

An extension of issue #335 
Adding bias to edge decoders.
Regression test results after my changes:
```
Dataset		Test Performance	Validation Performance	Total Time	Epoch Time/Seconds
OGB-MAG-NC	Acc: 0.4070		Acc: 0.4151		0:25:08		69.963
OGB-PROD-NC	Acc: 0.7254		Acc: 0.9137		0:46:33		108.104
```

[Feature] Add bias to edge decoder

---

graphstorm-processing/pyproject.toml

* poetry-core 2.0 seems to introduce some breaking changes, we try to prevent it from being used here. See also https://github.com/HumanSignal/label-studio-sdk/pull/382
Observed errors like the following in the GSP CI ([link](https://github.com/awslabs/graphstorm/actions/runs/12716501505/job/35454257790?pr=1099)):
```
[2025-01-10T21:37:40.821Z] AWS_BATCH_JQ_NAME=graphstorm-queue-v2
[2025-01-10T21:37:40.821Z] _=/usr/bin/env
[2025-01-10T21:37:40.821Z] jobId: 0e118ab7-26f4-4086-bcc2-6b4dfbcac20b
[2025-01-10T21:37:40.821Z] jobQueue: graphstorm-queue-v2
[2025-01-10T21:37:40.821Z] computeEnvironment: graphstorm-compute-v2
[2025-01-10T21:37:40.823Z] Cloning into 'graphstorm'...
[2025-01-10T21:37:41.380Z] REMOTE: …
```

[GSProcessing] Prevent poetry-core 2.0 from being used.

---

docs/source/cli/graph-construction/single-machine-gconstruct.rst
python/graphstorm/gconstruct/construct_graph.py
python/graphstorm/gconstruct/file_io.py
sagemaker/pipeline/README.md
sagemaker/pipeline/create_sm_pipeline.py
sagemaker/pipeline/execute_sm_pipeline.py
sagemaker/pipeline/pipeline_parameters.py
sagemaker/run/infer_entry.py
sagemaker/run/partition_entry.py
sagemaker/run/train_entry.py

* Add support for customizable SageMaker pipelines.
* We use one file to do the parameter parsing and validation, one to create the pipeline and one to execute.
* I used GenAI to create the first README, then hand-edited. 

[SageMaker] Add GraphStorm SageMaker Pipeline creation and execution

---

python/graphstorm/sagemaker/sagemaker_infer.py
sagemaker/launch/launch_infer.py
sagemaker/launch/launch_train.py

* Remove double download of model files and ensure models are downloaded under /tmp
* Tested by running a node classification job with ogb-arxiv data
Fixes #949

[SageMaker] Fix download location for model inference

---

sagemaker/launch/common_parser.py

* Our current default for region in SageMaker jobs will override users' local configuration. By setting this to None by default we respect the local config, while allowing users to specify a different region if needed.

[SageMaker] Make default region value be None, so AWS config takes precedence

---

.github/workflow_scripts/lint_check.sh
examples/sagemaker-pipelines-graphbolt/Dockerfile.processing
examples/sagemaker-pipelines-graphbolt/README.md
examples/sagemaker-pipelines-graphbolt/analyze_training_time.py
examples/sagemaker-pipelines-graphbolt/build_and_push_papers100M_image.sh
examples/sagemaker-pipelines-graphbolt/convert_arxiv_to_gconstruct.py
examples/sagemaker-pipelines-graphbolt/convert_ogb_papers100M_to_gconstruct.py
examples/sagemaker-pipelines-graphbolt/convert_ogb_papers100m_to_gconstruct.py
examples/sagemaker-pipelines-graphbolt/deploy_arxiv_pipeline.sh
examples/sagemaker-pipelines-graphbolt/deploy_papers100M_pipeline.sh
examples/sagemaker-pipelines-graphbolt/process_papers100M.sh
examples/sagemaker-pipelines-graphbolt/sagemaker_convert_papers100m.py
training_scripts/gsgnn_np/papers100M_nc.yaml

[Examples] SageMaker Pipelines distributed training

---

graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_hf_transformation.py
graphstorm-processing/tests/test_converter.py

* The `standard` transform was added to gconstruct in #1101 but we haven't added it to the gconstruct-to-gsp config converter.

[GSProcessing] Add standard numerical transformation to gconstruct config converter.

---

graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
graphstorm-processing/tests/test_row_count_utils.py

* Previously, if some node/edge types shared the same feature names, we would end up overwriting the original feature name dict because we shared it between types. 
* Now we create copies of the "data" dict for each type, and write the row counts directly to the corresponding type's dictionary, under the "row_counts" key.
* We also make the same fix for the graph structure entries (edges), although it's unlikely this would happen there.
* Finally used GenAI to generate some test cases for the file because it was untested before.

[GSProcessing] Fix ParquetRowCounter bug when different types had same-name features

---

graphstorm-processing/graphstorm_processing/config/label_config_base.py
graphstorm-processing/graphstorm_processing/constants.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_label_loader.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_category_transformation.py
graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/graphstorm_processing/graph_loaders/row_count_utils.py
graphstorm-processing/graphstorm_processing/graph_loaders/schema_utils.py
graphstorm-processing/graphstorm_processing/repartition_files.py
graphstorm-processing/tests/test_dist_heterogenous_loader.py
graphstorm-processing/tests/test_dist_label_loader.py

Fixes #1135 
Fixes #1138
* We guarantee ordering for node label classification by ordering the transformed label DF after processing by the NODE_INT_MAPPING id, and doing the same for masks.
* Because there is no guarantee for order when writing to Parquet from Spark _even for ordered Spark DataFrames_, we collect the labels and masks to a Pandas DF on the Spark leader, and write that using pyarrow.
* NOTE: DistPart requires at least N files to be present for every node/edge type, where N is the number of requested partitions. So when writing back the masks and label we still use the number of incoming partitions to create as many files.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

[GSProcessing] Enforce re-order for node label processing during classification

---

graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/graphstorm_processing/repartition_files.py

* Previously, during classification labels would be collected to the driver and written using pyarrow regardless of the type of mask that will be generated.
* To improve scaling, since we observed that the collect is not necessary when using custom masks, we revert to writing the label files using Spark, avoiding collecting to the driver and improving scalability.

[GSProcessing] Make label transformation use Spark for output instead of Pyarrow when using custom masks.

---

docs/source/cli/model-training-inference/configuration-run.rst

This PR modifies the sentence of `eval_fanout` explanation to highlight it will be used in inference too.

[Doc] Highlight inference in `eval_fanout` explanation

---

graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py

* Change the default Spark CSV parsing settings to follow RFC 4180 and match Pandas default

[GSProcessing] Change default quoting and parsing for CSV input

---

docs/source/cli/model-training-inference/distributed/sagemaker.rst
python/graphstorm/sagemaker/sagemaker_train.py
python/graphstorm/sagemaker/utils.py
sagemaker/launch/launch_hyperparameter_tuning.py
sagemaker/run/train_entry.py

Fixes https://github.com/awslabs/graphstorm/issues/1072
* We change train_entry and sagmaker_train so that when the user does not provide a value for the `--model-artifact-s3` argument, we rely on the SageMaker service to upload model artifacts. This makes it possible to run HPO and other jobs that rely on using the "official" SageMaker model paths.
* Add example launch script for HPO jobs and documentation.

[SageMaker] Add launcher and support for SageMaker HPO jobs

---

python/graphstorm/gconstruct/construct_graph.py
python/graphstorm/gconstruct/file_io.py
python/graphstorm/gconstruct/utils.py
tests/end2end-tests/data_process/data_gen.py
tests/end2end-tests/data_process/test.sh
tests/end2end-tests/data_process/test_data.py
tests/unit-tests/gconstruct/test_construct_graph.py
tests/unit-tests/gconstruct/test_gconstruct_utils.py

#996 
GConstruct will handle the corner cases when some edge files are empty files.
Note: DGL graph partition forces every edge type should have at least one edges.

Handle the cases when the input edge file(s) are empty

---

python/graphstorm/eval/eval_func.py
tests/unit-tests/test_eval_func.py

#1198 
The prediction results of regression tasks are always 2D tensors, even when the prediction target is a single float value for each node. If the label is a 1D tensor, it will trigger a tensor shape mismatch error. This PR fixes this error.

Fix the error case when the label is a 1D tensor for regression tasks

---

docs/source/install/env-setup.rst

Torch 2.1.0 and DGL 1.1.3 does not support Python >= 3.12.0.

[Doc] Add warning for previous dependencies installation

---

python/graphstorm/model/hgt_encoder.py
tests/unit-tests/test_nn_model.py

This PR fixes an HGT Encoder corner case, where the edge type with feature has 0 edge in a block. In such case the input of edge feature become empty dict, and will trigger an assertion error in the previous implementation. This PR handles this corner case.

[Fix] Fix an HGT Encoder Corner Case: 0 edge in a block

---

graphstorm-processing/docker/0.4.1/sagemaker/Dockerfile.cpu
graphstorm-processing/docker/0.4.1/sagemaker/log4j.properties
graphstorm-processing/docker/build_gsprocessing_image.sh
graphstorm-processing/graphstorm_processing/data_transformations/spark_utils.py

* The SageMaker image produces excessive logs. We use a config file to try to reduce those and bring in line with other execution environments.
* Will reduce the excessive yarn logs such as:
```
[/var/log/yarn/userlogs/application_1740449133449_0001/container_1740449133449_0001_01_000002/stderr] 25/02/25 02:08:49 INFO CodecConfig: Compression: SNAPPY
[/var/log/yarn/userlogs/application_1740449133449_0001/container_1740449133449_0001_01_000002/stderr] 25/02/25 02:08:49 INFO ParquetOutputFormat: ParquetRecordWriter [block size: 134217728b, row group padding size: 8388608b, validating: false]
[/var/log/yarn/userlogs/application_1740449133449_0001/container_1740449133449_0001_01_000002/stderr] 25/02/25 02:08:49 INFO ParquetWriteSupport: …
```

[GSProcessing] Reduce SageMaker logging

---

docker/sagemaker/Dockerfile.sm
docker/sagemaker/build_artifacts/start_with_right_hostname.sh

…
* Previously our SageMaker jobs would log errors like `ERROR: ld.so: object '/libchangehostname.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.` at the beginning of the job because the entry point script is trying to use a library (changehostname.c) that gets compiled at launch time, but we were using the wrong path there, which meant there was no library compiled.
* This PR fixes the path for the `changehostname.c`
* Our containers use a custom entry point, and code under `/opt/ml/code/` is usually reserved to be executed straight from SageMaker i.e. we do [this](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo-dockerfile.html#your-algorithms-training-algo-dockerfile-api-ep …

[Docker] Ensure hostname fix is at right place for SageMaker image. Use recommended paths for code

---

docs/source/advanced/sagemaker-pipelines.rst
sagemaker/pipeline/pipeline_parameters.py

[Docs] Add SageMaker pipeline docs

---

docs/source/cli/graph-construction/single-machine-gconstruct.rst
graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
graphstorm-processing/tests/test_converter.py
python/graphstorm/gconstruct/transform.py
python/graphstorm/gconstruct/utils.py
tests/unit-tests/gconstruct/test_construct_graph.py
tests/unit-tests/gconstruct/test_transform.py

* We add an explicit `no-op` transformation to GConstruct that can read delimited strings as vectors. 
* The previous no-op behavior when "transform" entry is not provided remains unchanged.
* Add docs and handling for conversion to GSProcessing.

[GConstruct] [GSProcessing] Allow no-op operation in gconstruct to read strings of delimited numbers as vectors

---

python/graphstorm/__init__.py

* Currently every time DGL is imported the torchdata deprecation warnings are printed. For logs with multiple workers and trainers we can have the same message repeated tens of times (once per DGL process), polluting the logs. 
* This PR filters out the warning since we are aware of the deprecation notice and it come from DGL and not graphstorm
Old behavior:
```
root@3ef2b8d262b3:/opt/ml/code# python
>>> import graphstorm
/opt/conda/lib/python3.11/site-packages/torchdata/datapipes/__init__.py:18: UserWarning:
################################################################################
WARNING!
The 'datapipes', 'dataloader2' modules are deprecated and will be removed in a
future torchdata release! Please see …
```

Don't print torchdata deprecation warnings

---

docs/source/advanced/imbalanced-labels.rst
python/graphstorm/gsf.py
python/graphstorm/model/loss_func.py
tests/end2end-tests/graphstorm-ec/test.sh
tests/end2end-tests/graphstorm-nc/test.sh
tests/unit-tests/test_gsf.py

* We use a condition to only set the decoder output dimension to 1 for focal loss, using num_classes for other cases.

Change decoder output definition so that focal loss does not require setting num_classes to 1.

---

graphstorm-processing/graphstorm_processing/data_transformations/dist_transformations/dist_label_transformation.py
graphstorm-processing/tests/test_dist_label_loader.py

* Previously, label column names that included colons in their name like `label:String`, which is how Neptune Analytics exports CSV columns, would trigger an SQL syntax error because of the way we defined the label DataFrame schema using an SQL string. 
For example with a column like `isFraud:Int`
```
[PARSE_SYNTAX_ERROR] Syntax error at or near ':'.(line 1, pos 3)
== SQL ==
idx: int, isFraud:Int: string
---^^^
```
* This PR programmatically defines the schema to avoid this issue.
* Modify a test to match the corner case.

[GSProcessing] Support `:` in label column names

---

docs/source/cli/model-training-inference/configuration-run.rst
python/graphstorm/trainer/ep_trainer.py
python/graphstorm/trainer/np_trainer.py

This PR comment out the warning message of `set return_proba to be true`, which is confusing during training pipeline. And revise the document of `return_proba` configuration to explain this configuration only works on inference output.

[Ehancement] Refactor `return_proba` warning message and document

---

docs/source/cli/model-training-inference/configuration-run.rst
python/graphstorm/__init__.py
python/graphstorm/config/argument.py
python/graphstorm/run/gsgnn_np/np_infer_gnn.py
python/graphstorm/sagemaker/sagemaker_infer.py
tests/end2end-tests/graphstorm-nc/check_emb.py
tests/end2end-tests/graphstorm-nc/test.sh
tests/unit-tests/test_np_infer_gnn.py

Fixes #1240 
* Add a top-level string input argument to the parser, `--infer-all-target-nodes`.
* When the user provides `--infer-all-target-nodes true` the set of nodes to run inference on returned from `get_node_infer_set` will be all the nodes for the target type.
* For now this is implemented only for `run/np_infer_gnn.py`.
* Used GenAI to create a unit test that mocks the main function because np_infer_gnn.py can only be executed as a script, there's no individual function we could test without refactoring. 
* Added e2e test scripts that check size of embeddings for test-only, and all-node embedding generation.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Add infer-all-target-nodes argument to trigger inference on all nodes in target node types

---

docs/source/cli/graph-construction/distributed/gsprocessing/input-configuration.rst
graphstorm-processing/graphstorm_processing/config/config_conversion/gconstruct_converter.py
graphstorm-processing/graphstorm_processing/graph_loaders/dist_heterogeneous_loader.py
graphstorm-processing/tests/resources/small_heterogeneous_graph/gconstruct-config.json
graphstorm-processing/tests/test_converter.py
graphstorm-processing/tests/test_dist_heterogenous_loader.py

Fixes https://github.com/awslabs/graphstorm/issues/1107
* Add handling for `*` in file paths, for local and S3 input in GSProcessing
* For local we glob files, for S3 we first list all files under prefix, then match file pattern

[GSProcessing] Handle `*` wildcards in filenames

---

tools/partition_graph_lp.py

This small PR replaces deprecated `numpy.in1d()` calls with `numpy.isin()` to resolve deprecation warnings while maintaining identical functionality in order to solve:
```python
DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
```
It also fixes a few typos along the way.

Resolve warnings of NumPy library

---

python/graphstorm/config/config.py
tests/unit-tests/test_config.py

The task id of link prediction subtask in multi-task learning setting may be too long when there are multiple edge types.
This led to errors when trying to save the embedding files, as the file names exceeded the maximum file name limit for file systems like ext4/XFS
See `Max filename length` in https://en.wikipedia.org/wiki/Ext4
Solution: trim the edge type information to keep the task id short.

[Bugfix] Fix the case when the subtask name is too long in multi-task learning

---

python/graphstorm/config/argument.py
python/graphstorm/config/config.py
tests/end2end-tests/graphstorm-nc/test.sh
tests/unit-tests/test_config.py

* We now save the training config file modified with runtime arguments in the model output

Save combined training config file with saved model artifacts

---

python/graphstorm/gconstruct/remap_result.py
tests/end2end-tests/data_process/test.sh

The bug was introduced in https://github.com/awslabs/graphstorm/pull/1163, where it saves relation2id_map.json into the emb output path. The remap script will mistakenly load the .json file.
Fix the bug

[BugFix] Fix a bug in remapping node embeddings, when shared fs is not avaliable

---

graphstorm-processing/graphstorm_processing/distributed_executor.py

When repartition failed on AWS infra, it will not save the transformed GSProcessing config. If users do repartition on SageMaker later, it will miss the tranformed GSProcessing config.
Resolve Issue: https://github.com/awslabs/graphstorm/issues/1300

[Bug Fix] Save transformed config before repartition

---

python/graphstorm/sagemaker/sagemaker_train.py
python/graphstorm/sagemaker/utils.py
sagemaker/launch/launch_train.py
tests/unit-tests/test_sagemaker_train_unit.py

* Currently we upload the entire model output from local to S3 at the end of SM model training. For X epochs that includes X directories, each with its own version of the model
* SageMaker however assumes the model output should be a single, self-contained model that can be used to deploy a model directly
* In this PR we determine the latest epoch from the list of directories, copy over the model weights, any embeddings, and config files (json/yaml/yml) to the standard SageMaker output directory, and only output the latest epoch in the out location chosen from the launch_train.py script
```
python launch_train.py --model-output-s3 s3://my-bucket/model-out --num-epochs 3
aws s3 ls s3://my-bucket/model-out
epoch-0/
epoch-1/
epoch-2/ …
```

[SageMaker] [breaking] Only upload latest epoch at the end of SageMaker training

---

python/graphstorm/gconstruct/transform.py
tests/unit-tests/gconstruct/test_construct_graph.py

* For GConstruct multi-column feature transformaion, current saved feat_dim_dict will only save the dimension of single column. Fix the code to save the concatenation of all the columns.
* Add the tests for multi-column feature transformation.

[Bug] Fix feat_dim for multi-column feature transformation

---

graphstorm-processing/graphstorm_processing/config/config_parser.py
graphstorm-processing/graphstorm_processing/distributed_executor.py
graphstorm-processing/tests/test_gsprocessing_config.py
python/graphstorm/dataloading/metadata.py
python/graphstorm/gconstruct/construct_graph.py
tests/sagemaker-tests/test_sagemaker_entry.py
tests/unit-tests/data_utils.py
tests/unit-tests/test_gsf.py
tests/unit-tests/test_metadata.py

* Add `add_reverse_edge` flag to handle the reverse edge case for real time inference endpoint. It will resolve the model loading issue during real time inference.
* Update the version string for gconstruct/gsprocessing.
* Test successfully on sagemaker with acm data.

[Bug] Fix real-time inference workflow when adding reverse edges

---

docs/source/cli/model-training-inference/real-time-inference.rst
sagemaker/launch/launch_realtime_endpoint.py

* To use NeptuneDB as a graph source, the endpoint needs to be able to communicate with the NDB instance, which is always placed inside a VPC. 
* With this PR we add the ability to select VPC subnets to place the endpoint in, and additional security groups that allow it to communicate with other resources in the VPC, e.g. an inference client that acts as an intermediate between NDB and SM endpoint, or directly communicate with NDB.
* We also add an option to provide the location of the entry point to use when launching the endpoint. This allows custom entry point locations to be used (e.g. we use this when using the launch script in isolation on a SageMaker notebook instance)
* Add two new optional arguments to …

[sagemaker] [rt-inference] Add option to deploy real-time endpoint into VPC, allow custom entry point location

---

graphstorm-processing/graphstorm_processing/distributed_executor.py

[GSProcessing] Ensure GSProcessing Entry point is backwards compatible with versions < 0.5
